### ISSUE TITLE
Use alpine as a base

### ISSUE THREAD

**Issue by TaiSHiNet** [kubernetes/git-sync#10]
I've tried alpine and size is reduced by ~100 mb but the mv version that comes with it doesn't have `--no-target-directory` option
Inputs?

**Comment by thockin** [comment]
I'd love to see this move to Alpine, but we need to identify all such
issues.

**Comment by stp-ip** [comment]
I have no capacity for the next 1.5 weeks, after that I might take a look. Anyone else having some time -> push ahead :smile:
