### ISSUE TITLE
Permission denied on /git/.git

### ISSUE THREAD

**Issue by kobozo** [kubernetes/git-sync#103]
E0803 13:22:58.321408       1 main.go:186] error syncing repo: error running command: exit status 1: "Cloning into '/git'...\n/git/.git: Permission denied\n"

My make command
`make container REGISTRY=local VERSION=latest`

The command I execute after build
`docker run --rm local/git-sync --repo=https://github.com/kubernetes/git-sync --branch=master --wait=30`

What I already tried
`
RUN mkdir /git/`
`RUN chmod 775 /git/
`

**Comment by thockin** [comment]
By default, git-sync runs as nobody, which requires you to set the --root flag.  I will change the default to $HOME/git.

Good catch.  All the tests set --root.
