### ISSUE TITLE
Git-Sync goes into a crash-loop forever if it fails after the initial clone

### ISSUE THREAD

**Issue by rlguarino** [kubernetes/git-sync#105]
A period of network issues seems to have surfaced an issue with git-sync for us.

Git-Sync can get its self stuck in a crash-loop if it exits after it's done the initial clone. It's very difficult to tell if this is failing after the clone on the initial sync or on a subsequent sync failure that is over the limit of `GIT_SYNC_MAX_SYNC_FAILURES`. Both cases results in the same error message, but we can expect both cases to happen in production. 

Here are some example logs:
```
ross@xenon:~$ kubectl logs kube-applier-6949c7675b-g626g -c git-sync
I0820 20:43:42.280722       1 main.go:164] starting up: ["/git-sync"]
I0820 20:43:47.214284       1 main.go:326] cloned ssh://<redacted>.git
I0820 20:43:47.215581       1 main.go:270] syncing to HEAD (c5d769d3bd5d18c99e22f0b3e06e1d1280170808)
E0820 20:43:52.225918       1 main.go:171] error syncing repo: error running command: exit status 128: "fatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n"

# Wait for Kubernetes to restart the pod.

ross@xenon:~$ kubectl logs kube-applier-6949c7675b-g626g -c git-sync
I0820 20:44:09.678487       1 main.go:164] starting up: ["/git-sync"]
E0820 20:44:09.679825       1 main.go:171] error syncing repo: error running command: exit status 128: "fatal: destination path '/git' already exists and is not an empty directory.\n"
```

From that point on the container will never work again, the entire pod must be restarted for it to work. Unless I'm mistaken the source of the errors isn't important since it could come from anything between git-sync and the git server being broken temporarily.

Should I instead try to force the pod to restart if git-sync restarts? That seems a little extreme to me.

**Comment by rlguarino** [comment]
Thanks for the quick response!

**Comment by rlguarino** [comment]
Is there a pre-release image somewhere?

**Comment by thockin** [comment]
I have not cut an image lately.  There's a new process for pushing
images, so I'll have to make some time to do that.  Waiting for one
more change.

**Comment by rlguarino** [comment]
Cool, I should be able to build it locally to test it.
