### ISSUE TITLE
GIT_SSH_COMMAND is overwritten

### ISSUE THREAD

**Issue by rlguarino** [kubernetes/git-sync#107]
I'm specifically trying to add `-vvv` to the ssh command by setting `GIT_SSH_COMMAND=ssh -vvv` in my pod. PR #29 added behavior that sets `GIT_SSH_COMMAND` instead of using a wrapper, which make sense but make this impossible.

I think it would be nice if `GIT_SSH_COMMAND` could still be used to set flags since that's how google and stackoverflow suggest people enable more verbose logs. However, I'm not sure if it would make sense to try and merge the user defined set of arguments with the settings git-sync needs to configure, it seems risky and prone to weird errors.

It might be easier to just add a new option to git-sync for enabling verbose ssh commands.

Does anyone have opinions?

**Comment by thockin** [comment]
We could take a different flags that was "extra git args" or something like
that and append it to GIT_SSH_COMMAND.  Need to think a bit about (and
test) escaping in case anyone embeds  quotes.

Help wanted, patches welcome...

**Comment by rlguarino** [comment]
I planned on submitting a Cl myself, I just wanted to have a chance for discussion before I wrote the code :thinking: 

It would be possible to do a best effort merging of the two sets of arguments but I'm not sure if the complexity is worth it. it would be very simple to add a completely new argument to git-sync for adding `-vvv` to ssh but it's not as flexible. Have there been requests in the past for anything like this?

**Comment by thockin** [comment]
No requests that I know of.  Adding an "extra args" flag seems
straight forward enough?

**Comment by rlguarino** [comment]
Yeah, I think adding extra args seems straightforward to me. I'll take a stab at that.

-

**Comment by thockin** [comment]
Ping?


/lifecycle frozen
/remove-lifecycle stale
