### ISSUE TITLE
Health check via /healthz endpoint

### ISSUE THREAD

**Issue by geekdave** [kubernetes/git-sync#113]
Just wondering if anyone has a preferred liveness probe / healthcheck command to ensure that a git-sync sidecar is healthy.  Without this, it seems there could be a risk of the git-sync sidecar silently failing, causing an expected config change not to be delivered.

**Comment by thockin** [comment]
I would be open to a PR which added an optional HTTP server inside
git-sync, with some configurable heuristics for what constitutes failure.
Alternately we already have (in master) `-max-sync-failures` which you can
set to 1 or 2.  That should trigger a crash of git-sync, which will be
flagged by kubernetes.  Less friendly, but workable.

**Comment by jacksontj** [comment]
A very basic liveliness probe is (hopefully) being added in #135 
So this issue likely should move to being the health-check issue to cover what heuristics/config/etc. we want to control what constitutes "healthy".
