### ISSUE TITLE
v2.0.2 not pushed to google_containers/git-sync

### ISSUE THREAD

**Issue by stp-ip** [kubernetes/git-sync#13]
Platform specific repos are up to date: https://gcr.io/v2/google_containers/git-sync-amd64/tags/list
The plain git-sync is not. v2.0.2 is still missing. https://gcr.io/v2/google_containers/git-sync/tags/list

cc @thockin

**Comment by thockin** [comment]
I need to fix Makefile to push both.  Sorry.
