### ISSUE TITLE
Metrics on git-sync state

### ISSUE THREAD

**Issue by jacksontj** [kubernetes/git-sync#130]
I have a variety of use-cases that require a sidecar such as this. For this type of a service (async syncer from git) I need to have some metrics so that I can monitor the health of the syncer.

Specifically I'm looking for:
- last_sync_time: this allows me to see that is in-fact pulling things
- total_error_count: this shows me that there are errors in pulling

I'm more than happy to submit the PR for this, I just wanted to get some input first -- specifically on how these metrics would be exposed. Personally I'm using prometheus exporters for most of my world, but this daemon doesn't currently have an HTTP endpoint -- would it be okay to add one? If not, what metrics format would be acceptable?

**Comment by stp-ip** [comment]
The metrics are useful as we've discussed, but I would say that a simple health endpoint might be easier to script around and also easier to call for liveness and readiness checks.
Question would be what is healthy?
* git-sync running?
* git-sync + successful sync?
* git-sync + successful sync, but not yet aborted due to failures?
* git-sync + successful sync + stale timeout while unlimited failures are allowed?

This needs a bit more discussion I think.

**Comment by jacksontj** [comment]
I think we want to a healthcheck PR *separate* from the metrics PR -- only because I think it'll require some more discussion.

I think "healthiness" is going to need to be somewhat configurable as what constitutes "healthy" varies from use-to-use (not to mention what you use the healthchecks for). As for configuring the check, maybe we allow for query args to the /healthz endpoint to control what it checks? 

Using the HC for k8s seems like overkill primarily because there are already options in git-sync to have the process die. So IMO if we want the healthcheck endpoint we should change the default exit behavior to not die. Right now if you have a failure (by default) git-sync dies and k8s is forced to start the pod again. It might be better to have git-sync fail a healthcheck so k8s can internally figure out who should get rescheduled first (IIRC it can allow for partially working pods?). My concern with both the "exit on first failure" and this healthcheck approach is that you can get into a situation where upstream git has an issue and all the pods roll without control.

**Comment by stp-ip** [comment]
Agreed with a separate PR, just wanted to give the context that this is about metrics, which might be used as a health indicator, but this workaround should be replaced by an actual health indicator. Thanks for noting this down.

One thing where we don't have something useful yet is to get readiness. So waiting for git-sync to finish the sync by waiting for the HC to turn to success would be an interesting use case. The second one would probably be with unlimited failures, but I agree this might already be handled with an aborted process already.

The difference with HC enabled liveness checks could be different failure modes by serving stale data. Aka failures syncing shouldn't kill the pod up to $stale_timeout, but anything else breaking the pod or health check should.
You don't want to code this into the liveness check, but we could code this into the health check.

First iteration should probably just solve the readiness issue. Aka 200 status on git-sync + successful sync. The rest could be done via unlimited failures and workarounds for now. Also waiting for some ideas from Tim here.

**Comment by thockin** [comment]
I think we need a do-nothing / handler that can be used for liveness.

I think we need a /healthz handler that needs semantics to be defined

I think we need metrics.

All are different.

As for how to sequence PRs, smaller is better, but I don't think readiness is @jacksontj 's problem to solve unless he wants.  A simple heuristic is "did the initial sync complete".  I bet there are corner cases, but as a start...

Ideally:

* add HTTP with do-nothing / handler (liveness)
* add simple /healthz with heuristic (readiness)
* add metrics
* add pprof
