### ISSUE TITLE
Doesn't work correctly for a branch other than master

### ISSUE THREAD

**Issue by ursuad** [kubernetes/git-sync#14]
When it starts up, it checks out the correct revision of the correct branch. The next run, it checks the latest revision of the master branch, even if it says it checks out from `origin/kubernetes`:

This are the variables that I'm running with:
I replaced the git repo user/name, because it's a private repo.
```
GIT_SYNC_BRANCH=kubernetes
GIT_SYNC_SSH=true
GIT_SYNC_DEST=git
GIT_SYNC_REPO=git@github.com:my-github-user/my-github-repo.git
```
And the logs:
```
I1026 17:09:48.023905       1 main.go:302] cloned git@github.my-github-user/my-github-repo.git
I1026 17:09:48.025887       1 main.go:251] syncing to HEAD (82abe61bbd80b47d2275178d7fed190a89ed621a)
I1026 17:09:48.809439       1 main.go:259] added worktree /git/rev-82abe61bbd80b47d2275178d7fed190a89ed621a for origin/kubernetes
I1026 17:09:49.259858       1 main.go:279] reset worktree /git/rev-82abe61bbd80b47d2275178d7fed190a89ed621a to 82abe61bbd80b47d2275178d7fed190a89ed621a
I1026 17:09:50.471179       1 main.go:353] update required
I1026 17:09:50.471212       1 main.go:251] syncing to HEAD (eb893e897072ba4b788e832b0ccab7138d860b06)
I1026 17:09:50.956608       1 main.go:259] added worktree /git/rev-eb893e897072ba4b788e832b0ccab7138d860b06 for origin/kubernetes
I1026 17:09:51.569854       1 main.go:279] reset worktree /git/rev-eb893e897072ba4b788e832b0ccab7138d860b06 to eb893e897072ba4b788e832b0ccab7138d860b06
```

**Comment by stp-ip** [comment]
Yeah I can confirm this issue.
When setting GIT_SYNC_BRANCH and GIT_SYNC_REV to a specific branch it seems to update to the right commit. The problem then is, that on each non updating run it throws an error such as: 
```error syncing repo: error running command: exit status 128: "fatal: '/etc/source/rev-13a93194f52c28591e2fee7e93666d8e1f7a4b50' already exists\n"```

**Comment by thockin** [comment]
You should only need to set one of branch or rev, I think.  I'll have to
check - that part predated my touching it :)

**Comment by thockin** [comment]
I can't repro this.  I am writing a test to cover this, and it passes just fine.  I'll post the test momentarily, and you can tell me what I am doing wrong...

**Comment by thockin** [comment]
test is #18

**Comment by stp-ip** [comment]
Will try to look at it later tonight or first thing tomorrow. Thanks for working on it.
