### ISSUE TITLE
Username environment variable not working.

### ISSUE THREAD

**Issue by xamox** [kubernetes/git-sync#145]
When trying to run just git-sync it prompts for username even though it exists in as an environment variable.  The strange thing is if I do a git-sync --help it will even show the default username it takes from the environment

```
  -username string
    	the username to use (default "REDACTED-gitsync\n")
```

My hack around was I just had to override my kube template to use:

```
          command: [ "/bin/sh", "-c", "--" ]
          args: [ "/git-sync -username REDACTED-gitsync" ]
```
and it worked.  It also used all the environment variables just fine, it just appears to be when not passing the username it does not like it.

**Comment by thockin** [comment]
Odd.  There's only one place where that is used in the code, and it's the
post-merge value, so if you see the value in --help, that's the value being
passed.

I don't have a setup to test this - any debug you can do would help...
