### ISSUE TITLE
How to create a .gitsyncignor for selective sync file

### ISSUE THREAD

**Issue by aleksey005** [kubernetes/git-sync#156]
Tell me if there is an opportunity to somehow filter the list from the repository files? Analog .dockerignore file?

**Comment by stp-ip** [comment]
Not sure I understand the full picture. What do you want to achieve?

**Comment by aleksey005** [comment]
I have a monolithic repository, I need to separate files from one another. I can put some files (php) in a container using a .dockerignor file, other files (css, js) I get a complete list in another workload over git-sync (full list files in repo). I have to delete them, because they are not needed there. If I could synchronize files selectively, it would spare me an extra step in pipeline.

**Comment by stp-ip** [comment]
Thanks for clarifying. This is more about git than about git-sync as we use the underlying git commands.
There is an open issue #54 related to this. Closing this here as a duplicate.
