### ISSUE TITLE
This repo should not require 'strict' status contexts.

### ISSUE THREAD

**Issue by cjwagner** [kubernetes/git-sync#159]
This repo currently has strict status context requirements enabled: https://github.com/kubernetes/test-infra/blob/b6737faf9879cba0aed01b782057aee47ad2664c/prow/config.yaml#L128

The `strict` setting corresponds to "Require branches to be up to date before merging" below:
![image](https://user-images.githubusercontent.com/5334145/54947756-4fd92e80-4ef8-11e9-8f94-d882c6a2a58a.png)

This setting requires that PR branches be rebased off the latest base branch commit meaning that if multiple PRs are open and one merges, other PRs must always rebase before merging. This is a simplistic method that GitHub provides for ensuring that PRs are tested against the most recent base branch commit before merging.

Tide uses a strictly superior method to provide the same guarantees without requiring PRs to be rebased whenever something else merges. This is possible because ProwJobs don't run on the PR head commits, they run on the merge commits and the base branch commit used in the merge is recorded. Tide can use this information to ensure that PRs are tested against the most recent changes without requiring PRs to be rebased unless there is an actual merge conflict.

Enabling the `strict` context requirements in a repo managed by Tide forces PR authors to rebase their PRs whenever something else merges even though this provides no benefit at all. Additionally, it is causing Tide to get stuck trying to merge some PRs because Tide doesn't know how to properly handle this merge requirement (since it doesn't makes sense to ever use this requirement with Tide).

Please remove this `strict: true` configuration ASAP:
https://github.com/kubernetes/test-infra/blob/b6737faf9879cba0aed01b782057aee47ad2664c/prow/config.yaml#L128

**Comment by thockin** [comment]
why not send one PR to remove them all?

**Comment by cjwagner** [comment]
> why not send one PR to remove them all?

That was my initial thought, but it was suggested that I open issues in the offending repos to get approval first and make sure that this isn't breaking some workflow or process, especially since I don't know why this setting was originally enabled.
We have `strict: true` in the config because that is what the repo was configured with when we switched to using the branchprotector. Previously this was configured through the GH settings UI, so there is no audit log explaining why the feature was enabled (at least that none that I can view).
I can remove the line from the config myself, that part is trivial, I'm just looking for approval with this issue and wanted to leave some sort of audit trail in the 2 affected repos. Sorry for the noise.

**Comment by thockin** [comment]
WRT DNS and git-sync, I have no idea why they were set and no
justification for leaving them set.

**Comment by cjwagner** [comment]
> WRT DNS and git-sync, I have no idea why they were set and no justification for leaving them set.

Ok, I'll switch it off for `k/git-sync` then (`k/dns` is already fixed). Thanks!

**Comment by thockin** [comment]
Thanks!
