### ISSUE TITLE
Funnel all `exec.Command` calls through `runCommand`

### ISSUE THREAD

**Issue by filmil** [kubernetes/git-sync#166]
`runCommand` has a nice facility that allows us to log the executed commands, which helps debugging.

There are code paths like say here: https://github.com/kubernetes/git-sync/blob/master/cmd/git-sync/main.go#L617 which don't use `runCommand` but call `exec.Command` directly, which miss out on this opportunity.

Seem like it would be good to have all code paths that subprocess a command go through `runCommand` at least to get the benefit of the debug logging.

**Comment by thockin** [comment]
Agree.  All exec's should use runCommand
