### ISSUE TITLE
this is a example for initContainers

### ISSUE THREAD

**Issue by ilanni2460** [kubernetes/git-sync#169]
`apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Secret
  metadata:
    name: git-creds
    namespace: dev4
  data:
    ssh: !removed-ssh-data!
    known_hosts: Z2l0bGFiLjUxeGYuY24gc3NoLXJzYSBBQUFBQjNOemFDMXljMkVBQUFBQkl3QUFBUUVBczU0RmtGR1Z1TXMxV0c4dlVTUDh1NlYwL0V3cHI4K1J5TEpLYU5URFVQeUd2VzVQK1Uvdm0vRXRNTTI0c2ZuZXNmb3dobTBNM2VGNdGVCR09kOEVY222S2IrS1lRSFVZdGY1NUhMeGdQbHdYTmF6R2QvVlR6MFRSckZHUmdwRlJQN0RITmVuL1EzTkMrQlBJMFBtaW83OE0xWjdVZUp0Qmo5ekxVa1V5T0EwVFAvTmJPOEw2MVhCS3F4eHAwMklTVEFtT012YU1qY3F1c0FBeDBPcy9QaEV2b3diOCt3cmNZdk1vZ3c3d1E0VnBOMEx3SWVCa2lWWVE4NlRMdnlRajhkRXduVzlMc1A3c00yQlhrOHFuWVlOdXRjSHFMUE1RZ0dvK2E3blFSS2xaZVBSSTQxcC9TQ054R2tudE1RPT0=

- apiVersion: v1
  kind: Service
  metadata:
    name: git-svc
    namespace: dev4
    annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port: '8080'
  spec:
    type: NodePort
    ports:
    - name: debug-port
      port: 7070
    - name: http-pub-port
      port: 8080
      targetPort: 8080
    - name: http-private-port
      port: 9191
      targetPort: 9191
    sessionAffinity: ClientIP
    sessionAffinityConfig:
      clientIP:
        timeoutSeconds: 10800
    selector:
      app: git-dm

- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: git
    namespace: dev4
  spec:
    selector:
      matchLabels:
        app: git-dm
    replicas: 1
    revisionHistoryLimit: 5
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
    template:
      metadata:
        labels:
          app: git-dm
          version: v-1
      spec:
        terminationGracePeriodSeconds: 60
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                    - key: "app"
                      operator: In
                      values: 
                      - git-dm
                topologyKey: "kubernetes.io/hostname"
        initContainers:
        - name: git-sync
          image: gcr.azk8s.cn/google-containers/git-sync:v3.1.1
          securityContext:
            runAsUser: 65533
          volumeMounts:
          - name: git-source
            mountPath: /tmp/git
          - mountPath: /etc/git-secret
            name: git-secret
          env:
          - name: GIT_SYNC_REPO
            value: git@gitlab.ilanni.com:devops/certfile.git
          - name: GIT_SYNC_SSH
            value: "true"
          - name: GIT_SYNC_PERMISSIONS
            value: "0777"
          - name: GIT_SYNC_ONE_TIME
            value: "true"
          - name: GIT_SYNC_BRANCH
            value: "master"
          - name: GIT_SYNC_DEPTH
            value: "1"
          - name: GIT_SYNC_DEST
            value: certfile
        containers:
        - name: git
          image: docker.ilanni.com/ilanni/job-executor:develop
          imagePullPolicy: Always
          lifecycle:
            preStop:
              exec:
                command:
                - sh
                - -c
                - "sleep 5"
          resources:
            requests:
              memory: "512Mi"
              cpu: "0.5"
            limits:
              memory: "2560Mi"
              cpu: "4"
          env:
          - name: JAVA_OPTS
            value: "-Xmx2048m"
          - name: CHANGE_TIME
            value: "+0"
          volumeMounts:
          - name: git-source
            mountPath: /opt/soft/jar/config/
        securityContext:
          fsGroup: 65533
        volumes:
        - name: git-source
          emptyDir: {}
        - name: git-secret
          secret:
            secretName: git-creds
            defaultMode: 288`

**Comment by stp-ip** [comment]
Removed your ssh data. But you should change it either way. Don't publish ssh data in public.

Also not sure, what you are asking.
Additionally please make use of the code feature within Github to make code formatting and reading easier. Some information around this: https://help.github.com/en/articles/basic-writing-and-formatting-syntax#quoting-code

**Comment by ilanni2460** [comment]
@stp-ip ok,tks.
i only share this

**Comment by willzhang** [comment]
good share!
