### ISSUE TITLE
Sidecar produces zombies when git repo is unreachable

### ISSUE THREAD

**Issue by zvirinsky** [kubernetes/git-sync#170]
By default if git-sync is unable to reach git repo it fails which is causing pod failing. To avoid this I tried to use `-max-sync-failures=-1,` but in case of repo unavailability git-sync produces zombie processes and sometimes a huge amount of them.
In case of successful initial sync and `-max-sync-failures=-1` git-sync process shouldn't produce a child for each re-sync iteration in case repo is temporary unavailable.

**image:** k8s.gcr.io/git-sync:v3.1.1

```
65533    28507 24506  0 May14 ?        00:00:00 [ssh] <defunct>
65533    28508 24506  0 May14 ?        00:00:00 [ssh] <defunct>
65533    28509 24506  0 May14 ?        00:00:00 [ssh] <defunct>
65533    28510 24506  0 May11 ?        00:00:00 [ssh] <defunct>
65533    28515 24506  0 May11 ?        00:00:00 [ssh] <defunct>
65533    28517 24506  0 May13 ?        00:00:00 [ssh] <defunct>
65533    28518 24506  0 May11 ?        00:00:00 [ssh] <defunct>
65533    28520 24506  0 04:00 ?        00:00:00 [ssh] <defunct>
65533    28524 24506  0 May11 ?        00:00:00 [ssh] <defunct>
65533    28527 24506  0 May14 ?        00:00:00 [ssh] <defunct>
65533    28528 24506  0 May14 ?        00:00:00 [ssh] <defunct>
65533    28529 24506  0 May11 ?        00:00:00 [ssh] <defunct>
65533    28530 24506  0 May13 ?        00:00:00 [ssh] <defunct>
65533    28531 24506  0 May14 ?        00:00:00 [ssh] <defunct>
65533    28533 24506  0 May11 ?        00:00:00 [ssh] <defunct>
65533    28535 24506  0 May14 ?        00:00:00 [ssh] <defunct>
65533    28540 24506  0 May13 ?        00:00:00 [ssh] <defunct>
65533    28541 24506  0 May14 ?        00:00:00 [ssh] <defunct>
65533    28543 24506  0 May14 ?        00:00:00 [ssh] <defunct>
65533    28544 24506  0 May13 ?        00:00:00 [ssh] <defunct>
65533    28549 24506  0 May14 ?        00:00:00 [ssh] <defunct>
65533    28550 24506  0 May14 ?        00:00:00 [ssh] <defunct>
65533    28553 24506  0 May13 ?        00:00:00 [ssh] <defunct>
65533    28554 24506  0 May11 ?        00:00:00 [ssh] <defunct>
65533    28561 24506  0 May14 ?        00:00:00 [ssh] <defunct>
...
```
After 5 days running:
```
$ ps -ef | grep defunct | wc -l 
18091
```

**Comment by trnl** [comment]
@thockin, is this simlar to #55?

**Comment by thockin** [comment]
If this is still happening, can you post logs?

**Comment by thockin** [comment]
So the issue here is real, I can force it to happen.  Git runs ssh and seems to not always clean up.  Classic "pid 1" problem.

The real trick is what to do about it.

We can't just catch all SIGCHLD, because that races with real code that wants to know exit statuses.

We can either:

a) detect that we are pid1 and fork ourselves, leaving the parent as an init process to catch unhandled SIGCHLD (which we either vendor or write ourselves)
b) vendor and run an actual init program that does this - there are many out there
c) periodically sweep for zombies
