### ISSUE TITLE
git-sync can not  support proxy?

### ISSUE THREAD

**Issue by fumanne** [kubernetes/git-sync#180]
when manually, (git clone git@xxx.github.com/yyy.git )  I use proxy configure like this:
in ~/.ssh/config
```
Host xxx.github.com
  User git
  ProxyCommand nc -x proxy:1080 %h %p
```
But When use git-sync, how to do it?
Can it support this function?

**Comment by thockin** [comment]
I have no direct experience with setting this up, so I'll need some help.  How do you think it should work?  What should the CLI be to set this up in the most general way possible?

We set the homedir to /tmp, so could you simply mount your custom ssh config to /tmp/.ssh/config?

**Comment by fumanne** [comment]
em。。。I have mount ssh config  and it looks work.  thank you 😁

Tim Hockin <notifications@github.com> 于2019年10月26日周六 下午12:37写道：
