### ISSUE TITLE
Sync bare repository from several remotes

### ISSUE THREAD

**Issue by mattiasb** [kubernetes/git-sync#184]
At my work we have a need for a containerized service to sync git repositories. In most cases what we need is to keep a single repository checkout in sync with upstream master.

We have another use case though. We want to have a bare reference repository (as described [here](https://support.cloudbees.com/hc/en-us/articles/115001728812-Using-a-Git-reference-repository)) in sync with several upstreams. As I understand it this isn't possible to accomplish with current `git-sync`, but would you take a PR for it? Maybe it's just fundamentally out of scope for what git-sync is trying to be?

**Comment by thockin** [comment]
I read the docs and I admit I still don't quite understand it.

I am not against it on any principle, just that I don't know what's involved.

**Comment by thockin** [comment]
In fact taking a look at it, it may be that --mirror would be a better way to run all of git-sync.  Maybe we could drop the distinction between branch, tag, and hash

**Comment by mattiasb** [comment]
I realized we had a couple other more domain specific use cases so I started developing an in-house solution. When I get it up and running I'll ask for permission to publish it here (which should be okay). I'll try to remember this issue and send a link to my work then, there might be some ideas worth porting over. :)
