### ISSUE TITLE
Use git --mirror

### ISSUE THREAD

**Issue by thockin** [kubernetes/git-sync#202]
I have found that using git --mirror makes it easier to resolve symbolic revs.  We can then get rid of the --branch flag and JUST keep --rev.

I propose a v4 with breaking changes (flags)

**Comment by stp-ip** [comment]
Will read up on this.

**Comment by thockin** [comment]
I have a branch that  seems to work.  Breaking it up into smaller commits :)

**Comment by thockin** [comment]
Superseded by #284

**Comment by thockin** [comment]
Fixed in #691
