### ISSUE TITLE
Exit status 1 when connection fail

### ISSUE THREAD

**Issue by dignajar** [kubernetes/git-sync#214]
Hi,
I'm running `git-sync` with another application inside the same pod (Kubernetes pod), and sometimes I have connectivity error with my Git server and the container `git-sync` exit with status 1, it's possible to set up some kind of retries and not exit?

Thanks

**Comment by stp-ip** [comment]
Set GIT_SYNC_MAX_SYNC_FAILURES to -1?
But at least the first sync needs to succeed.

**Comment by dignajar** [comment]
I will try it, thank you!
