### ISSUE TITLE
Using user and group nobody creates chmod error

### ISSUE THREAD

**Issue by stp-ip** [kubernetes/git-sync#22]
Due to nobody:nobody not having enough permissions the chmod fails and a ssh secret file can't be used.
Currently working on using defaultMode so that can be removed completely.

**Comment by stp-ip** [comment]
Current workaround until I figured out why defaultMode doesn't work:

On the git-sync container set the securityContext to:
```
securityContext:
  runAsUser: 0
```

**Comment by guang** [comment]
thanks! ran into the exact same error

**Comment by stp-ip** [comment]
Should be fixed with #25
