### ISSUE TITLE
Trigger sync via by http rest manually from external

### ISSUE THREAD

**Issue by cforce** [kubernetes/git-sync#226]
There is already a service port cfg, but no docs for any endpoint. Would be great to trigger that sync via a call on this container port published.

**Comment by thockin** [comment]
Can you explain why?  Whats wrong with the periodic syncs?

How would you guard this against malicious use - some form of auth or rate-limiting?  

I'm not against an option for this, but it needs to be justified and thoroughly designed.

**Comment by cforce** [comment]
The idea was to of course to initiate the pull of a refresh copy controlled external, because the application itself has no way of monitoring changes on the file system, so it need to trigger that also from external.

**Comment by thockin** [comment]
I don't understand - the pull isn't instantaneous, so even if you could trigger it you would have to wait for the update.  But more than that - this doesn't explain why periodic pulls are not sufficient.

And my main concern stands - How would you guard this against malicious use?  Is "external" truly external or actually "within the pod" ?

**Comment by thockin** [comment]
I'll close this for now - feel free to reopen it if you want to reconsider the idea.

**Comment by mostafahussein** [comment]
Hello @thockin , This would be useful if you would like to integrate this in some sort of CI job so you can trigger the sync under specific conditions. regarding the authentication, I don't mind managing it myself. I guess this issue #149 is similar

**Comment by trulede** [comment]
Would it be an alternative to interrupt the sleep (I presume [here](https://github.com/kubernetes/git-sync/blob/d9120f7a40e976b846400fe5eb9728877771fdf1/cmd/git-sync/main.go#L766)) with an OS signal? That signal might come from another container or Kubectrl.

**Comment by thockin** [comment]
You want to send a signal to the process and have it immediately do a sync?

I don't outright object to that (not to HTTP, but this is even easier to justify), but I would like to know the use-case.

**Comment by thockin** [comment]
If you want to discuss, can you open a new issue with more details on use-case?
