### ISSUE TITLE
git-sync permission deny with dir has files other container write in

### ISSUE THREAD

**Issue by pyfdtic** [kubernetes/git-sync#236]
i run git-sync with airflow as a sidecar. git-sync sync dags in remote gitlab repo. 

when airflow load dags , it write pyc files into repo dir as root, while git-sync run as git-sync user. Next time , when git-sync try to update file from remote repo, it report `"error"="error removing directory: unlinkat` error and exit, the same time the airflow service  into error state and exit.

what should i do? is there a way to disable the remove old dir behavior ?

**Comment by pyfdtic** [comment]
i fixed this by annotated the remove old repo dir code.

**Comment by jmorgan415** [comment]
@pyfdtic Hi, I'm having the same issue.  Can you explain exactly what you did?  Thanks in advance!
