### ISSUE TITLE
submodules only sync when main repo changed

### ISSUE THREAD

**Issue by sepich** [kubernetes/git-sync#241]
Hello,
We have a repo, with a folder being submodule.
On start of v3.1.5 everything is synced.
If I update submodule repo - no sync happens.
Then I update any file in main repo - it syncs both main repo content and submodule dir.
Is it possible to also monitor submodules repos for updates?
Thank you.

**Comment by thockin** [comment]
This is more challenging.  I'm not super familiar with submodules - can you help me by writing up an e2e test case (see test_e2e.sh) that demonstrates what you'd like to see work?  Then at least I can think about how to implement it.

**Comment by sepich** [comment]
While trying to write a test to reproduce, this turned out to be 'as designed'.

More info:
I thought that it is possible to have submodule to point to branch, not commit_id.
But it turned out my workflow with committing to submodule from actual sub-folder of main repo lead to update of submodule ref_id. 
That's why i was getting git-sync to update on commit on main repo, because there was also an update of submodule commit_id pushed together with my changes.
There is no way to have submodules update by itself (new commits in branch) because actual commit_id is tracked in `.git/modules/sub/refs/heads/master` and should be updated in main repo anyway.
Thank you, now i better understand how it works.

**Comment by thockin** [comment]
That's how I thought it worked, but I appreciate the follow-through to
prove it!
