### ISSUE TITLE
docker run from readme.md got "/tmp/git/.git: Permission denied" 

### ISSUE THREAD

**Issue by snd3r** [kubernetes/git-sync#245]
```
11:03 # docker run -v /tmp/git-data:/tmp/git k8s.gcr.io/git-sync:v3.1.5 --repo=https://github.com/kubernetes/git-sync --branch=master --wait=30
INFO: detected pid 1, running init handler
I0427 08:15:44.534916      12 main.go:322]  "level"=0 "msg"="starting up"  "args"=["/git-sync","--repo=https://github.com/kubernetes/git-sync","--branch=master","--wait=30","sh"]
I0427 08:15:44.534974      12 main.go:575]  "level"=0 "msg"="cloning repo"  "origin"="https://github.com/kubernetes/git-sync" "path"="/tmp/git"
E0427 08:15:44.536551      12 main.go:348]  "msg"="failed to sync repo, aborting" "error"="error running command: exit status 1: \"Cloning into '/tmp/git'...\\n/tmp/git/.git: Permission denied\\n\""
```

Hi guys, what am I doing wrong?

**Comment by gkarthiks** [comment]
/assign

hi @snd3r I was trying in my local, it seems fine. The problem seems to be in your `/tmp/git/.git` location. 

Can you try cloning into the a different location?

**Comment by EdKingscote** [comment]
I saw this too - you either need to make /tmp/git-data world writable outside the container to make the example work out of the box. Should this container be taking care of ensuring that permissions are properly established?

**Comment by gkarthiks** [comment]
I will leave that decision to @thockin and @stp-ip

**Comment by gkarthiks** [comment]
but in my opinion, that location for cloning repo can be changed. It doesn't need to be in a place where the container's service account is not permissioned to write. So adding the additional logics for that is certainly useful but very less valuable.

**Comment by EdKingscote** [comment]
I was running in to this in the context of docker-compose and the permissions alignment with volumes had me scratching my head for a while - here is a working config example - nginx isn't quite doing the right things inside a browser due to content type issues I think, but curl serves up files just fine. Hopefully someone finds the nugget useful.

```
docker-compose.yml
version: '3.7'

services:
  gitsync:
    image: registry/gitsync:tag
    restart: always
    environment:
     - GIT_SYNC_REPO=https://github.com/kubernetes/git-sync
     - GIT_SYNC_BRANCH=master
     - GIT_SYNC_WAIT=30
     - GIT_SYNC_ROOT=/tmp/gitwebdata/
    volumes:
     - www:/tmp:rw

  nginx:
    image: nginx:1.17.7-alpine
    restart: always
    ports:
     - "8080:80/tcp"
    volumes:
     - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
     - www:/tmp
    depends_on:
     - gitsync

volumes:
  www:

---------------------------
nginx.conf

server {
    listen 80;
    listen [::]:80;
    server_name _;

    root /tmp/gitwebdata/;
    location / {

    }
}
```

**Comment by sascha-wolf** [comment]
I'm encountering the same issue. It seems to only occur when using a docker volume.

I can easily reproduce the issue using the following commands:

```
$ docker volume create git-sync-test

$ docker run -v git-sync-test:/tmp/git k8s.gcr.io/git-sync:v3.1.6 --repo=https://github.com/kubernetes/git-sync/
```

Which leads to the following output:

```
INFO: detected pid 1, running init handler
I0622 13:26:56.934211      12 main.go:321]  "level"=0 "msg"="starting up"  "args"=["/git-sync","--repo=https://github.com/kubernetes/git-sync/"] "pid"=12
I0622 13:26:56.934340      12 main.go:574]  "level"=0 "msg"="cloning repo"  "origin"="https://github.com/kubernetes/git-sync/" "path"="/tmp/git"
E0622 13:26:56.937497      12 main.go:347]  "msg"="failed to sync repo, aborting" "error"="error running command: exit status 1: { stdout: \"\", stderr: \"Cloning into '/tmp/git'...\\n/tmp/git/.git: Permission denied\\n\" }"
```

**Comment by gkarthiks** [comment]
I don't think this is an issue. But rather we can change the readme to have some other location. Thoughts @thockin ?

**Comment by thockin** [comment]
Here's my understanding:

When you run docker with `-v  /tmp/git-data:/tmp/git` and /tmp/git-data does not exist, docker will create that directory (as root!) and then bind-mount it into your container.  If your container is not running as root, it can not write to that directory.

Unfortunately, there's not much I can do.  Docker is not smart enough to realize that the container is not root when it makes that dir.  Inside the container run, I literally am not root, so I can't chmod it, even if I wanted to.

You have to make sure the directory is writeable by whatever user your are going to run git-sync as (which by default, is not root).

Sorry - this is working as intended, or at least as specified by Docker.  There's literally nothing I can do (I think, unless I am misunderstanding the problem).

**Comment by sascha-wolf** [comment]
@thockin the issue also occurs when using docker volumes, in which case I as a user do not have any control about the access rights (AFAIK). This makes docker volumes effectively unusable with `git-sync`.

Is this worthy of being tracked in a separate issue?

**Comment by rodriwasabi** [comment]
I guess there should be an article on how to overcome this issue. At least explaining why and how to fix.
Besides that, it is great to know that it runs fine on their machines ;)

**Comment by thockin** [comment]
https://github.com/kubernetes/git-sync/pull/402
