### ISSUE TITLE
Syncing branches of submodules

### ISSUE THREAD

**Issue by dtpryce** [kubernetes/git-sync#250]
We would like to be able to set the branch for the submodule as seen here https://git-scm.com/docs/git-submodule#Documentation/git-submodule.txt--bltbranchgt

So that git-sync will pick up commits on that branch specifically rather than any commits only on master branch.

When trying to set the branch in the main repo for .gitmodules config git-sync is unable to find the commits.

If this isn't getting fixed is there a workaround?

**Comment by thockin** [comment]
The -b flag is part of `submodule add`, which records the SHA (at least that is how I understand it) into your repo.  git-sync just calls `git submodules update` - what additional flags would you pass to that command to do what you want?

Try running with --v=5 - it will show you every git command it runs, so you can recreate the flow by hand.  If there's a git option we need to run, show me where and what, so I can understand it and fix it.

**Comment by dtpryce** [comment]
Well we want to be able to change that branch not just fix it using the -b flag ... so expected to be able to update the .gitsubmodules file with the branch option but still only master branch was read from in git-sync or sync errors. This very well might be user error. 

Are you suggesting that we would have to re-add the submodule any time we would want to change the branch?

**Comment by thockin** [comment]
On Fri, Jul 31, 2020 at 4:47 AM David Pryce <notifications@github.com>
wrote:

> Well we want to be able to change that branch not just fix it using the -b
> flag ... so expected to be able to update the .gitsubmodules file with the
> branch option but still only master branch was read from in git-sync or
> sync errors. This very well might be user error.
>

I am not a deep expert in git submodules.  The way I understand them and
have used them and just ran quick tests to confirm is that the "parent"
repo carries a reference to the specific SHA.  Even if the submodule'd
repo changes, you always get that same SHA

Can you show me a series of git commands that does what you want?


> Are you suggesting that we would have to re-add the submodule any time we
> would want to change the branch?
>

I'm not suggesting anything - I am saying that I don't know if what you are
asking for is really a thing that git does, and if it is, I don't know the
magic invocation.  Please show me!

**Comment by neutronth** [comment]
It looks like a similar use case of mine (https://github.com/kubernetes/git-sync/issues/265)
which I introduce the PR to add a feature that git registered submodules could be synced with remote tracking branch.

Suggestions are welcome.

**Comment by dtpryce** [comment]
> On Fri, Jul 31, 2020 at 4:47 AM David Pryce ***@***.***> wrote: Well we want to be able to change that branch not just fix it using the -b flag ... so expected to be able to update the .gitsubmodules file with the branch option but still only master branch was read from in git-sync or sync errors. This very well might be user error.
> I am not a deep expert in git submodules. The way I understand them and have used them and just ran quick tests to confirm is that the "parent" repo carries a reference to the specific SHA. Even if the submodule'd repo changes, you always get that same SHA Can you show me a series of git commands that does what you want?
> Are you suggesting that we would have to re-add the submodule any time we would want to change the branch?
> I'm not suggesting anything - I am saying that I don't know if what you are asking for is really a thing that git does, and if it is, I don't know the magic invocation. Please show me!

I am trying but not entirely sure either because not a submodule expert either ;P 

But I think we want git-sync to be able to leverage this option https://git-scm.com/docs/git-submodule#Documentation/git-submodule.txt--bltbranchgt

And then within the main repo when git-sync performs it would be able to sync not just from the child repo master branches (which is what it does now, you cannot set the branch option in .gitsubmodules without breaking git-sync). Does that help? 

I think what @neutronth is suggesting is the same use case.

**Comment by stp-ip** [comment]
As far as my understanding goes even with a branch set for a given submodule it will reference a specific commit within the parent repo's commits.
So technically it feels hacky to update submodule references without the underlying parent actually committing the change.
As far as I understand the branch option for submodules specifies which branch of the submodule it tracks for any subsequent submodule updates via "git submodule update".

Let me know, if I'm missing something.

**Comment by dtpryce** [comment]
You are right but when using submodules in git-sync and trying to set the branch, then updating as you mention hence parent is pointing at the hash you have asked on a branch you wish. For some reason git-sync does not seem to find those commits (even with depth > 1). Maybe some screenshots / clear workflow would help?

**Comment by stp-ip** [comment]
Do you have a public parent repo by chance?

So the issue is that git-sync fails pulling in the submodule as the referenced commit isn't available?

**Comment by dtpryce** [comment]
> Do you have a public parent repo by chance?
Sadly not, private within an org


> So the issue is that git-sync fails pulling in the submodule as the referenced commit isn't available?
I think so yes, it all appears to work with the repositories and their updates but then git-sync fails as you mention.

**Comment by stp-ip** [comment]
What's the specific error that git-sync returns? Can't test it tonight, but will try to do it in the following days.

**Comment by dtpryce** [comment]
Has been a while since I tried this ... I can reproduce next week? i think it was a sync fail and wait for retry.

**Comment by stp-ip** [comment]
Were you able to reproduce this @dtpryce ?

**Comment by dtpryce** [comment]
> Were you able to reproduce this @dtpryce ?

Not regularly and we worked around it in the end. Will re-open if it becomes an issue again, thanks for the discussion!!
