### ISSUE TITLE
Could not read from remote repository ! Please make sure you have the correct access rights 

### ISSUE THREAD

**Issue by BeamerIsHere** [kubernetes/git-sync#251]
I'm trying to mount a tfs repo using ssh key as secret using git-sync, and the repo got cloned successfully at first then I've tried again the same yaml deployment file second time container getting failed after some restarts saying..

msg"="failed to sync repo, aborting" "error"="error running command: exit status 128: \"Cloning into '/tmp/git'...\\nfatal: Could not read from remote repository.\\n\\nPlease make sure you have the correct access rights\\nand the repository exists.\\n\""
But I'm pretty sure I haven't changed anything ( ssh key, known_hosts or the deplyment file) This is my yaml file. 

`
apiVersion: apps/v1
kind: Deployment
metadata:
  name: git-sync
spec:
  selector:
    matchLabels:
      demo: git-sync
  template:
    metadata:
      labels:
        demo: git-sync
    spec:
      volumes:
      - name: git-secret
        secret:
          secretName: git-creds
          defaultMode: 256
      containers:
      - name: git-sync
        image: k8s.gcr.io/git-sync:v3.1.5
        ports:
        - containerPort: 22
        args:
         - "-ssh"
         - "-repo=ssh://tfs.insidecompany.com:22/Power-DSM/Docs/_git/techdocs"
         - "-dest=techdocs"
         - "-branch=master"
         - "-depth=1"
        securityContext:
          runAsUser: 65533 # git-sync user
        volumeMounts:
        - name: git-secret
          mountPath: /etc/git-secret
          readOnly: true
      securityContext:
fsGroup: 65533 # to make SSH key readable
``

**Comment by thockin** [comment]
Try running with --v=5 and looking at logs - that should show every command it runs.
