### ISSUE TITLE
overcoming passphrase request

### ISSUE THREAD

**Issue by bicepjai** [kubernetes/git-sync#257]
git-sync asking for passphrase request. how to overcome this issue when using ssh key solution

container output
```
I0725 04:42:51.980070 1 main.go:270] starting up: ["/git-sync"]

E0725 04:42:52.196201 1 main.go:294] error syncing repo: error running command: exit status 128: "Cloning into '/git'...\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n"
```

manually ran the command and found that it was asking for passphrase.
```
/ $ ./git-sync 
I0725 04:37:30.544506      36 main.go:270] starting up: ["./git-sync"]
Enter passphrase for key '/etc/git-secret/ssh': 
```

**Comment by thockin** [comment]
You need to use a non-interactive form of auth.  You can specify a password or you can use a SSH key that doesn't need a passphrase or something like that.  How do you want it to work, given that it is automated and a human is not usually sitting in front of it?
