### ISSUE TITLE
Strategy to load big repos

### ISSUE THREAD

**Issue by gokula-krishna-dev** [kubernetes/git-sync#259]
Hi all,

I am having issues with cloning a big repo. The start time is almost 5min. I tried a shallow clone with depth 1. But issue with that is if there's a new changes with more than 1 commit, all other changes are discarded. Is it possible to load the initial sync with depth 1 and then unshallow later?

Thanks in advance.

**Comment by thockin** [comment]
If you ask for depth 1, aren't you asking for other commits to be discarded?  I don't know what the problem there is?

You could do something like `--depth=100` maybe?

**Comment by gokula-krishna-dev** [comment]
I resolved the issue by squash merging the PRs. Now my pod's start time is faster and I have all changes. Thank you for your time @thockin
