### ISSUE TITLE
Way for syncing multiple repositories & branches?

### ISSUE THREAD

**Issue by bukowa** [kubernetes/git-sync#261]
I am thinking about syncing all branches on multiple repos - all the time updating branches to sync (while they are created or deleted). Is there a place for that in the @git-sync library?

**Comment by thockin** [comment]
What do you mean by all-branches?  What are you going to do with that?  What do you want checked out?

For example, is your consumer going to try to modify the repo?  Is it going to try to checkout branches?  Or is it going to make its own clones of the repo or maybe use worktrees against the repo?

Anything that modifies the git-sync directory (including making commits or changing branches) will likely be un-done by git-sync.

On the other hand, the idea of having git-sync use `clone --mirror` is maybe feasible - then you could manually create your own worktrees for various commits (though at that point git-sync is not doing much for you :)

Explain more?

**Comment by stp-ip** [comment]
Second the points from Tim.

Not sure that it is the intended use case of git-sync. Git-sync is more about syncing one specific repo and reference (branch, tag, hash) to a location on disk.

Keeping different repositories, branches etc. in sync was not really the main intention.
Syncing writable repositories between each other might lead to issues/conflicts on frequent use. So it would be great to learn more about your specific use case.

**Comment by bukowa** [comment]
Thanks for your input. I see your point - it's a totally different thing from what `git-sync` is trying to acomplish, but to clarify my question: i was thinking of read-only mode, where the process that is control of syncic specified repository and it's ref - accepting a request - could stop syncing - for the time of processing the request (for ex. creating zip file at the current state of the repostiory & ref).

**Comment by thockin** [comment]
It's not really what git-sync was intended for, and it would take some
careful thinking.  Your last comment is still a bit hypothetical - do
you have a concrete use-case you are trying to solve for?

**Comment by thockin** [comment]
Does #285 do what you want?

**Comment by bukowa** [comment]
Hey not really. What i had in mind: there is a service for ex. in kubernetes that each new deployment can ask for specific git repository and it's branch / commit. Initcontainer would do that, receving ZIP file response in return -> saving that to PV. What i am doing now is mounting SSH keys to initcontainer that is running below script:

````go
func main() {
	destDir := flag.String("dir", "/repos", "zip dir destination")

	flag.Parse()
	if len(os.Args) < 2 {
		log.Fatal("you must provide repository urls as arguments, ex. 'gitcloner https://gitlab.com... https://github.com...'")
	}

	var wg = &sync.WaitGroup{}

	for _, arg := range os.Args[1:] {
		arg := arg
		wg.Add(1)
		go func() {
			defer wg.Done()

			branch, host, path := fatalParseUri(arg)
			name := pkg.ParseRepoName(path)
			uri := fmt.Sprintf("git@%s:%s.git", host, path)

			dir := fatalTempDir(".", name+"*")
			git := fatalGitDir(dir)

			git("init")
			git("remote", "add", "origin", uri)
			git("fetch", "--depth=1", "origin", branch)
			git("checkout", "FETCH_HEAD")
			fatalZipDir(dir, ppath.Join(*destDir, name))
			fatalRemoveAll(dir)
		}()
	}
	wg.Wait()
	log.Print("done")
}

// https://gitlab.com/group/project@tag
func ParseURI(uri string) (branch, host, path string, err error) {
	u, err := url.Parse(uri)
	if err != nil {
		return
	} else if u.Host == "" {
		err = fmt.Errorf("empty host: %s", uri)
		return
	}
	s := strings.Split(u.Path, "@")
	if len(s) == 1 {
		branch = "master"
	} else {
		u.Path = s[0]
		branch = strings.Join(s[1:], "@")
	}
	return branch, u.Host, u.Path, nil
}

func ParseRepoName(path string) string {
	var s string
	p := ppath.Clean(path)

	if strings.Contains(p, `\`) {
		s = `\`
	} else if strings.Contains(p, `/`) {
		s = `/`
	} else {
		return p
	}

	v := strings.Split(p, s)
	if len(v) == 1 {
		return v[0]
	}
	return v[(len(v)-1)]
}

````

**Comment by thockin** [comment]
I think your solution is going to be cleaner than adding this to git-sync :)
