### ISSUE TITLE
feature request: poll method

### ISSUE THREAD

**Issue by ngtuna** [kubernetes/git-sync#264]
Internal environments aren't allowed to receive GH webhook (ex. build engine can't be public) thus poll-based is alternative solution. Any idea to support poll-based for git-sync ?

**Comment by thockin** [comment]
Hi, I am not sure what you are asking for.  This is already polled - webhook support is for git-sync to send webhooks, not receive them.

In short git-sync is basically:

```
while true; do
    if changed in remote
        git fetch
        git worktree
    fi
    sleep
done
```
