### ISSUE TITLE
A duplicate directory named rev?

### ISSUE THREAD

**Issue by qwerty10110** [kubernetes/git-sync#267]
First of all, awesome container.  Totally saving my project.

When I look inside the container, I notice that two directories are created.  A myapp.git/ directory, and a rev-b12bfrandomstring/ file with all the same content.  Is this expected or known behavior?  Can it go away?

**Comment by neutronth** [comment]
It's by design.

Your `myapp.git` is a symlink to the `rev-<SHA hash>`, that's why their contents are identical.

See: https://github.com/kubernetes/git-sync/blob/dcf169c10abb8823e1eb961de24a9b13b1ce39af/cmd/git-sync/main.go#L493

**Comment by thockin** [comment]
Glad it works!

@neutronth is correct - to do atomic updates we use worktrees (the SHA-named dir) and do atomic symlink flips.  If you watched an update happen you'd see two SHA dirs while it all gets checked out and then the symlink would change and then the old dir would be removed.
