### ISSUE TITLE
-webhook-success-status option cannot be disabled in v3.1.7

### ISSUE THREAD

**Issue by puneetkatyal** [kubernetes/git-sync#288]
It seems there are multiple issues with the `-webhook-success-status` option:

1. the input validation requires the value to be > 0
2. the default value is that of the env variable `GIT_SYNC_WEBHOOK_SUCCESS_STATUS` i.e 200
3. the option help still recommends setting this to -1 to disable

I'm not sure if I am missing something here but it looks like this option cannot be disabled in v3.1.7 to make webhook calls fire-and-forget.

**Comment by thockin** [comment]
Try k8s.gcr.io/git-sync/git-sync:v3.2.0
