### ISSUE TITLE
provide current checked out rev 

### ISSUE THREAD

**Issue by cforce** [kubernetes/git-sync#296]
I would like  to retrieve current used revision / hash of head commit  (e.g if i used no tag but head)  via env of k8 cfg property.

**Comment by thockin** [comment]
There's no way to edit env vars once a process has started.  You can
readlink() on the git-root/dear though.  Is that sufficient?

**Comment by thockin** [comment]
Hmm, it seems we add a prefix to that link.  We have not historically treated it as an API, but what if we did?  If I could guarantee that readlink() on the `dest` would produce the git SHA, would that do what you need?  It might be in v4 as a guarantee, though

**Comment by cforce** [comment]
I am using it based on init container. How could i access the this API and then write value so it can be consumed from the next container ?

**Comment by thockin** [comment]
To be clear: I am not suggesting this yet, but what if the API was
simply "call readlink" on the repository (git-sync publishes through a
link) - the value of the link would be the SHA.  We can't make that
through an env var - it's just not something k8s can express.

**Comment by cforce** [comment]
I solved it by injecting from outside on podrestart
