### ISSUE TITLE
--timeout arg expects type int whereas all other time arguments are type duration

### ISSUE THREAD

**Issue by vanugrah** [kubernetes/git-sync#297]
Hello! 👋 

Firstly, absolutely love this project. Kudos! With that out of the way, I noticed an inconsistency between time format specification across the different command line arguments. Specifically, the following arguments all expect a duration type: 

- `--wait`
- `--webhook-timeout`
- `--webhook-backoff`

The only time argument that defies this convention is `--timeout` which expects an int type instead of a duration. Not sure if this is an intended inconsistency so I thought I'd bring it up.

**Comment by thockin** [comment]
Fixing it is a breaking change, so I plan to do that in a v4 release.
In fact, I have it fixed in my working branch :)

**Comment by vanugrah** [comment]
Splendid! Glad you are aware of this. I just noticed that the `--wait` property is of type float instead of duration as well. Is that also being handled in the v4 release?

**Comment by thockin** [comment]
https://github.com/thockin/git-sync/commit/498e790405b7fac9b9970e29ae1c1f48d2e2f751

I need to get back to this and do it properly.

I'll close this issue now, but thanks for raising it.
