### ISSUE TITLE
the `git-sync` user does not have permission to run git-sync in a docker container

### ISSUE THREAD

**Issue by haiyanmeng** [kubernetes/git-sync#308]
The `git-sync` user does not have permission to run git-sync in a docker container. However, it works if the docker container is run as root with the `-u 0` docker flag.

Here is the docker command I ran and the returned error:
```
$ sudo rm -rf /tmp/git-data && \
    docker run -it \
    -v /tmp/git-data:/tmp/git \
    registry/git-sync:tag__linux_amd64 \
    --repo=https://github.com/haiyanmeng/acm \
    --branch=master \
    --period=10s --root=/tmp/git/root -v=5

INFO: detected pid 1, running init handler
I1118 02:50:35.524784      11 main.go:417]  "level"=0 "msg"="starting up"  "args"=["/git-sync","--repo=https://github.com/haiyanmeng/acm","--branch=master","--period=10s","--root=/tmp/git/root","-v=5"] "pid"=11
E1118 02:50:35.524958      11 main.go:425]  "msg"="ERROR: can't make root dir" "error"="mkdir /tmp/git/root: permission denied"  "path"="/tmp/git/root"

```

Here is the `.dockerfile-linux_amd64` file generated during the execution of `make container REGISTRY=registry VERSION=tag`:
```
$ cat .dockerfile-linux_amd64 
FROM k8s.gcr.io/debian-base:v2.0.0

RUN apt-get update \
    && apt-get -y upgrade \
    && apt-get -y install \
        ca-certificates \
        coreutils \
        socat \
        git \
        openssh-client \
    && rm -rf /var/lib/apt/lists/*

# By default we will run as this user...
RUN echo "git-sync:x:65533:65533::/tmp:/sbin/nologin" >> /etc/passwd
# ...but the user might choose a different UID and pass --add-user
# which needs to be able to write to /etc/passwd.
RUN chmod 0666 /etc/passwd

ADD bin/linux_amd64/git-sync /git-sync

WORKDIR /tmp
USER 65533:65533
ENTRYPOINT ["/git-sync"]
```

**Comment by thockin** [comment]
When you tell docker "-v /tmp/git-data:/tmp/git" it will make a directory if needed. Docker runs as root.  Make sure that /tmp/git-data exists and is writeable by whatever UID you are running as.

You can look at the test_e2e.sh for proof that it works :)

**Comment by haiyanmeng** [comment]
After checking test_e2e.sh, it seems that I need to run docker as the current user, instead of as `git-sync`:
https://github.com/kubernetes/git-sync/blob/22f69061ff3dbc963a2a6153c6513edf1d19983b/test_e2e.sh#L125

**Comment by thockin** [comment]
You should be able to run it as ANY user as long as that user can
write to the `--root`
