### ISSUE TITLE
git push back to git repo

### ISSUE THREAD

**Issue by willzhang** [kubernetes/git-sync#309]
i want git push back to git repo in git-sync container, but i can't do that.

i use argocd and change the yaml files image tag in git repo, i want use git-sync pull the yaml repo and commit it then push it back.

i found the .git is not in shell.git , so how can i do that

```
# ll -a
total 4
drwxr-xr-x. 4 root root   87 Nov 26 04:52 .
drwxr-xr-x. 3 root root   18 Nov 26 04:52 ..
drwxr-xr-x. 8 root root  181 Nov 26 05:34 .git
drwxr-xr-x. 8 root root 4096 Nov 26 04:54 rev-d005215721521a0041266e028140e90c4c963669
lrwxrwxrwx. 1 root root   44 Nov 26 04:52 shell.git -> rev-d005215721521a0041266e028140e90c4c963669
```

what i want is :

```
git add -A
git commit -m "change image tag"
git push origin master
```

**Comment by thockin** [comment]
This is really not what git-sync is for.  It exists to sync itself to some
"upstream".  Making local changes and pushing them is a race and (even if
the git repo were set up how you want) likely to spuriously fail.

Also, as you notes, the repo so checked out as a worktree, locked to a
certain sha, so this is just not going to do what you want .

If you think the local tree is mutable, why not just 'git clone' it
yourself and manage the t that way?  Git-sync is not offering much value to
you, I think.
