### ISSUE TITLE
Request: Cut new point release

### ISSUE THREAD

**Issue by freget** [kubernetes/git-sync#311]
Hi together,

(this is strictly speaking not an issure, please apologize)

[This](https://github.com/kubernetes/git-sync/commit/410c5950b891e7c3873b0d66f6b0f65167676a2b) commit adds the new GIT_SYNC_HOOK_COMMAND option. This option would be really cool to have in production.

Would it be possible to cut a new point release from the current master anytime soon? 

Thanks a lot!

**Comment by thockin** [comment]
I can kick this off.

**Comment by thockin** [comment]
Staging is available at gcr.io/k8s-staging-git-sync/git-sync:v3.2.1, promo PR is https://github.com/kubernetes/k8s.io/pull/1467

**Comment by freget** [comment]
Cool, thank you!

**Comment by thockin** [comment]
https://github.com/kubernetes/git-sync/releases/tag/v3.2.1
