### ISSUE TITLE
Clarification about async webhook behavior

### ISSUE THREAD

**Issue by wimo7083** [kubernetes/git-sync#312]
The documentation states the following:

```markdown
Webhooks are executed asynchronously from the main git-sync process. If a webhook-url is configured, when a change occurs to 
the local git checkout a call is sent using the method defined in webhook-method (default to POST). git-sync will continually attempt 
this webhook call until it succeeds (based on webhook-success-status). If unsuccessful, git-sync will wait webhook-backoff (default 
3s) before re-attempting the webhook call.
```

I'm pretty new to golang and trying to understand the coordination between [`Webhook.Send`](https://github.com/kubernetes/git-sync/blob/release-3.x/cmd/git-sync/main.go#L467) and the locking actions that occur in webhook.go.

I prematurely pressed while typing my thoughts out.

It appears that when the main for loop performs a send action, it triggers a mutex lock with a deferred unlock. It appears this mutex lock is solely for coordination of the hash value, and not for coordination of the local git tree.

I'm still having trouble understanding how coordination between the webhook and main goroutines for the actual codebase repository is enforced. How do you ensure the webhook has completed prior to performing the next iteration of `syncRepo`?

**Comment by thockin** [comment]
>  How do you ensure the webhook has completed prior to performing the next iteration of syncRepo?

We don't.  If the upstream changes fast enough it's possible we don't send some of the individual hashes.  We do not block syncs on notifications.  If your webhook receiver is slow, that's on you.

Is there a problem you are having?

**Comment by wimo7083** [comment]
No, there's no problem. I just wanted to understand what is expected. 

In my case I think it would be considered slow because my webhook action will take < 30 seconds. I could probably coordinate the the duration of the GIT_SYNC_WAIT to be longer than GIT_SYNC_WEBHOOK_TIMEOUT.

**Comment by thockin** [comment]
Is it critical that syncs be delayed until the webhook completes?

You could futz with the wait, but I'd appreciate to understand the use-case if I am missing something useful :)

**Comment by wimo7083** [comment]
I don't think the syncs need to be delayed, I just want to make sure I understand this magic.

My use case:
I'm using this git-sync'd single repo as configuration for a gitops process for different variations of this same type of config. 

The format of the repo is such that I cannot git-sync the repo to each host but must use the correct overlay for each variant (different types of static files, different environments).

The listening webhook would run an ansible playbook or a salt highstate, which would ensure the configs are properly updated. We currently use ansible to template and deploy these configs, but this is part of a learning exercise to see if templating can be split from deployment so that we can add some better testing.

**Comment by wimo7083** [comment]
Thank you for the answers.

**Comment by thockin** [comment]
Got it.  So if your actuation webhook took 30 seconds and upstream changed again during that, we would queue up the subsequent hashes and when your webhook finished (assuming it does not ACK the HTTP request early) the most-recent hash would be sent as another webhook.

It does raise an interesting question - if git-sync died and restarted during your long webhook but after a 2nd change, would we restart and send another webhook?  Or would you effectively "lose" the event?  I have a feeling you would lose it.  Maybe we need to send a webhook always at startup...

**Comment by wimo7083** [comment]
Since I'm using volume mounts with emptyDir, I'm getting a webhook at startup, I just assumed that was a feature. :)

**Comment by thockin** [comment]
I'm more concerned about crash-and-restart, where the repo already exists
at a hash, but no webhook was sent for that hash
