### ISSUE TITLE
Can't create .netrc file -- How to specify location of .git-credentials file?

### ISSUE THREAD

**Issue by etho201** [kubernetes/git-sync#319]
When I try to run git-sync without specifying `runAsUser: 0` I get:

```bash
│ INFO: detected pid 1, running init handler                                                                                                                               │
│ ERROR: can't create .netrc file: can't configure git credential helper: Run(git config --global credential.helper store): exit status 255: { stdout: "", stderr: "error: │
│ stream closed
```

The default user in this container can only write to files in the `/tmp` directory (not it's own home directory). Is there a way to tell git-sync where the `.git-credentials` file should be stored? The user cannot write to the home directory, so instead I would like to store this file in the `/tmp` directory.

I see git can be configured for this with `git config credential.helper 'store --file=/tmp'`. How can I pass in an argument to git-sync to achieve this?
> https://git-scm.com/docs/git-credential-store

Alternatively, is it possible to store and read the git-credentials as a Kubernetes secret? I didn't see anything in the documentation on this.

**Comment by thockin** [comment]
Can you show the other args you pass (flags or env) to git-sync ?

**Comment by thockin** [comment]
Also - what specific git-sync version are you using?

**Comment by etho201** [comment]
I'm running it inside a Grafana pod. Using the latest git-sync release (k8s.gcr.io/git-sync/git-sync:v3.2.1).

```bash
extraEmptyDirMounts:
  - name: grafana-dashboards
    mountPath: /tmp/git-sync
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: 'default'
        options:
          path: /tmp/git-sync/repo/dashboards
          foldersFromFilesStructure: {{ .Values.folder_structure }}
extraContainers: |
  - name: git-sync
    image: k8s.gcr.io/git-sync/git-sync:v3.2.1
    securityContext:
      runAsUser: 0
    volumeMounts:
      - name: grafana-dashboards
        mountPath: /tmp/git-sync
    args:
      - -repo={{ .Values.grafana_dashboards_repo }}
      - -branch={{ .Values.grafana_dashboards_revision }}
      - -username={{ .Values.grafana_dashboards_username }}
      - -password={{ .Values.grafana_dashboards_pat }}
      - -root=/tmp/git-sync
      - -dest=repo
```

**Comment by thockin** [comment]
Can you expand the variables?  I can't reproduce this.

```
$ docker run -ti --entrypoint=/bin/sh gcr.io/k8s-staging-git-sync/git-sync:v3.2.1
Unable to find image 'gcr.io/k8s-staging-git-sync/git-sync:v3.2.1' locally
v3.2.1: Pulling from k8s-staging-git-sync/git-sync
597de8ba0c30: Already exists 
a2d71b870be5: Pull complete 
14caff585d41: Pull complete 
40f2c94c37ef: Pull complete 
8d621ab7d329: Pull complete 
08c222e42f0d: Pull complete 
Digest: sha256:245b348ee71fdca329e7b50176d65f339eaa561e35b7ff081a29f2e6744034b7
Status: Downloaded newer image for gcr.io/k8s-staging-git-sync/git-sync:v3.2.1
$ whoami
git-sync
$ id
uid=65533(git-sync) gid=65533 groups=65533
$ echo $HOME
/tmp
$ pwd
/tmp
$ touch file
$ mkdir dir   
$ git config --global credential.helper store
```

or

```
$ docker run -ti gcr.io/k8s-staging-git-sync/git-sync:v3.2.1 -repo=http://github.com/kubernetes/git-sync -username=foo -password=bar -branch=master -root=/tmp/git-sync -dest=repo
INFO: detected pid 1, running init handler
I0105 20:25:13.810318      11 main.go:430]  "level"=0 "msg"="starting up"  "args"=["/git-sync","-repo=http://github.com/kubernetes/git-sync","-username=foo","-password=bar","-branch=master","-root=/tmp/git-sync","-dest=repo"] "pid"=11
I0105 20:25:13.810407      11 main.go:694]  "level"=0 "msg"="cloning repo"  "origin"="http://github.com/kubernetes/git-sync" "path"="/tmp/git-sync"
I0105 20:25:14.701674      11 main.go:586]  "level"=0 "msg"="syncing git"  "hash"="b631e429460d5e80e18b4073922e6eb6d3ac4c6d" "rev"="HEAD"
I0105 20:25:15.274231      11 main.go:607]  "level"=0 "msg"="adding worktree"  "branch"="origin/master" "path"="/tmp/git-sync/rev-b631e429460d5e80e18b4073922e6eb6d3ac4c6d"
I0105 20:25:15.297705      11 main.go:630]  "level"=0 "msg"="reset worktree to hash"  "hash"="b631e429460d5e80e18b4073922e6eb6d3ac4c6d" "path"="/tmp/git-sync/rev-b631e429460d5e80e18b4073922e6eb6d3ac4c6d"
I0105 20:25:15.297758      11 main.go:635]  "level"=0 "msg"="updating submodules"  
```

I see that you are setting `-root` does the non-root user/group (65533 by default) have write access to the volume you are mounting?

**Comment by etho201** [comment]
The variables are to a private repo within an organization, so it wouldn't help if I expand those variables, but they are just like any other repo that can be accessed via a PAT.

I haven't tried `65533` to see if it can create in /tmp/git-sync, but I have tried as the Grafana user (id for that is `472`). That user is only able to create files in the /tmp directory. Again, this user (for whatever reason) is unable to create files in its own home directory (`/home/grafana`); thus the reason for wanting to change where the .git-credentials file will be stored (in this case, it should work fine if I store it in `/tmp` since the user can write there).

I have considered specifying `/home/grafana` as an emptyDir, (set those permissions to fsGroup 472) and run as user `472`. I think that will work, but ultimately it may be more useful to be able to set the value of `git config credential.helper`.

**Comment by thockin** [comment]
Let's take it apart.

If you don't set any runAsUser it's going to run as 65533.

User 65533's $HOME dir is /tmp.

User 65533 can write to /tmp, as we have both observed.

So where is it trying to write a .netrc file?  Well it's not even getting that far.  The error you listed shows it can't even create the .gitconfig file.

Running the container manually and running `git config --global credential.helper store` by hand I see a .gitconfig file created in /tmp.

That suggests to me that either: a) You are not running as the 65533 user (so your $HOME is something else); or b) your /tmp/ is not writable, but you say otherwise.

Are you SURE you are running as the default user ID?  If you want to run as another user you need to set HOME or tell git-sync to add the user to /etc/passwd.

```
host $ docker run -ti -u 999 --entrypoint=/bin/sh gcr.io/k8s-staging-git-sync/git-sync:v3.2.1
$ git config --global credential.helper store
error: could not lock config file //.gitconfig: Permission denied

host $ docker run -ti -e HOME=/tmp -u 999 --entrypoint=/bin/sh gcr.io/k8s-staging-git-sync/git-sync:v3.2.1
$ git config --global credential.helper store
```

Compounding this is the fact that the git error message is "stream closed".  I don't know why it would get that.  I can't reproduce it.  Is it always that error?

**Comment by etho201** [comment]
Thank you! Breaking it down really helped! Especially where you mentioned: "If you want to run as another user you need to set HOME or tell git-sync to add the user to /etc/passwd."

Since I know user `472` (grafana) cannot write to its own home directory, I needed to set the environment variable for home to a directory it can write to. This worked:

```bash
extraContainers: |
- name: git-sync
  image: {{ .Values.gitsync_image }}
  securityContext:
    runAsUser: 472
  volumeMounts:
    - name: grafana-dashboards
      mountPath: /tmp/git-sync
  args:
    - -repo={{ .Values.grafana_dashboards_repo }}
    - -branch={{ .Values.grafana_dashboards_revision }}
    - -username={{ .Values.grafana_dashboards_username }}
    - -password={{ .Values.grafana_dashboards_pat }}
    - -root=/tmp/git-sync
    - -dest=repo
  env:
    - name: HOME
      value: /tmp
```

Another thing that worked is to explicitly set the git-sync user to `65533`. I believe since I was deploying git-sync inside a Grafana pod, the helm chart for Grafana overrode the user to 472 (by default). If I tell it to run as `65533` then git-sync's home dir is `/tmp` as you stated.

```bash
extraContainers: |
- name: git-sync
  image: {{ .Values.gitsync_image }}
  securityContext:
    runAsUser: 65533
  volumeMounts:
    - name: grafana-dashboards
      mountPath: /tmp/git-sync
  args:
    - -repo={{ .Values.grafana_dashboards_repo }}
    - -branch={{ .Values.grafana_dashboards_revision }}
    - -username={{ .Values.grafana_dashboards_username }}
    - -password={{ .Values.grafana_dashboards_pat }}
    - -root=/tmp/git-sync
    - -dest=repo
```

Thank you for your help!

**Comment by thockin** [comment]
I wonder if I should just set HOME unilaterally?  I think so.  It would
have avoided this entirely.
