### ISSUE TITLE
Proposal: Generate an error file

### ISSUE THREAD

**Issue by nan-yu** [kubernetes/git-sync#326]
# Objective
The goal of this feature is to export the git-sync errors to a file which can be shared by other sidecar containers.

# Motivation
The current git-sync process outputs the error information to standard out, which is inaccessible from outside the container. Users have to dump the logs using `kubectl logs` in order to check the error details in the git-sync process. This proposal provides users the capability to check the errors directly from other sidecar containers.

# Goals
- Share the most recent git-sync error with other sidecar containers.

# Non-Goals
- This proposal does not intend to redirect all logging information to a file.
- The error file only keeps the most recent error. It is not supposed to be used as the error history.

# High-level Design
There will be a new flag to indicate whether to generate the error file. If the flag is turned on, the error file may or may not exist depending on the sync status.
If sync succeeds, the file will be removed. Otherwise, the file will be created or overwritten with the most recent error message.
To guarantee atomic update to the error file, we always write to a temp file first and then rename that to the error file. This enables the client to know the file has been updated even if the contents are the same.
The client will poll on the error file to get the error message on failures.

# Implementation details
## Add a flag for `--error-file`
```
var flErrorFile = flag.String("error-file", envString("GIT_SYNC_ERROR_FILE", ""), "the path to the error file where to dump the most recent error details")
```

### 1. Before calling `os.Exit()` with a non-zero code
There are some common steps if the process exits abnormally with a non-zero code: output the error to standard error, print the usage information (optional), export the error to the error file and exit the process. Therefore, we extract these steps into a function.
```
// handleError prints the error to the standard error, prints the usage if the `printUsage` flag is true,
// exports the error to the error file and exits the process with the exit code.
func handleError(exitCode int, printUsage bool, format string, a ...interface{}) {
	fmt.Fprintf(os.Stderr, format, a...)
	if printUsage {
		flag.Usage()
	}
	exportError(fmt.Sprintf(format, a...))
	os.Exit(exitCode)
}
```

Below are the cases when the process exits with a non-zero code:
- [Flag initialization errors](https://github.com/kubernetes/git-sync/blob/release-3.x/cmd/git-sync/main.go#L253)
  If any flag is invalid, export the error before exiting by calling `handleError(1, true|false, "ERROR: can't ....: %v\n", err)`

- [Unhandled pid1 errors](https://github.com/kubernetes/git-sync/blob/release-3.x/cmd/git-sync/main.go#L239): exit via `handleError(127, false, "ERROR: unhandled pid1 error: %v\n", err)`

- Errors in [`syncRepo`](https://github.com/kubernetes/git-sync/blob/release-3.x/cmd/git-sync/main.go#L456)
```
log.Error(err, "too many failures, aborting", "failCount", failCount)
exportError(err.Error())
os.Exit(1)
```

- Errors in [`revIsHash`](https://github.com/kubernetes/git-sync/blob/release-3.x/cmd/git-sync/main.go#L480)
```
log.Error(err, "can't tell if rev is a git hash, exiting", "rev", *flRev)
exportError(err.Error())
os.Exit(1)
```

### 2. Before [retry](https://github.com/kubernetes/git-sync/blob/release-3.x/cmd/git-sync/main.go#L460)
```
log.Error(err, "unexpected error syncing repo, will retry")
exportError(err.Error())
log.V(0).Info("waiting before retrying", "waitTime", waitTime(*flWait))
cancel()
```

## When to clean up the error file
If the sync is successful, we need to clean up the error file generated from the previous sync if it exists. There are three cases to clean up the file:
### 1. If it is a [one-time](https://github.com/kubernetes/git-sync/blob/release-3.x/cmd/git-sync/main.go#L475) sync
```
if *flOneTime {
	deleteErrorFile()
	os.Exit(0)
}
```

### 2. If `--rev` is a [commit hash](https://github.com/kubernetes/git-sync/blob/release-3.x/cmd/git-sync/main.go#L482)
```
else if isHash {
	log.V(0).Info("rev appears to be a git hash, no further sync needed", "rev", *flRev)
	deleteErrorFile()
	sleepForever()
}
```

### 3. Before the [next sync](https://github.com/kubernetes/git-sync/blob/release-3.x/cmd/git-sync/main.go#L489)
```
failCount = 0
deleteErrorFile()
log.V(1).Info("next sync", "wait_time", waitTime(*flWait))
```

## Validation, export and delete functions
The validation function for the new flag:
```
// validateErrorPath validates if the parent directory of `--error-file` exits and creates one if not exits.
// It also checks if the parent directory has the read and write permission.
func validateErrorPath(errPath string) {
	errDir := filepath.Dir(errPath)
	if errDirInfo, err := os.Stat(errDir); err != nil {
		fmt.Printf("The error parent path %s doesn't exist. Attempt to create it\n", errDir)
		if err = os.MkdirAll(errDir, 0755); err != nil {
			fmt.Fprintf(os.Stderr, "ERROR: can't create directory: %v\n", err)
			os.Exit(1)
		}
	} else if !errDirInfo.IsDir() {
		fmt.Fprintf(os.Stderr, "ERROR: The error parent path %s is not a directory\n", errDir)
		os.Exit(1)
	} else if err = syscall.Access(errDir, syscall.O_RDWR); err != nil {
		fmt.Fprintf(os.Stderr, "ERROR: can't access %s: %v\n", errDir, err)
		os.Exit(1)
	}
}
```

The export function:
```
// exportError writes the error content to the error file.
func exportError(content string) {
	if *flErrorFile != "" {
		tmpFile, err := ioutil.TempFile(os.TempDir(), "err-")
		if err != nil {
			fmt.Fprintf(os.Stderr,"Cannot create temporary file: %v\n", err)
			os.Exit(1)
		}

		if _, err = tmpFile.WriteString(content); err != nil {
			fmt.Fprintf(os.Stderr, "ERROR: can't write to temporary file: %v\n", err)
			os.Exit(1)
		}
		defer func() {
			if err := tmpFile.Close(); err != nil {
				fmt.Fprintf(os.Stderr, "ERROR: can't close temporary file: %v\n", err)
			}
		}()

		if err := os.Rename(tmpFile.Name(), *flErrorFile); err != nil {
			fmt.Fprintf(os.Stderr, "ERROR: can't rename to error file: %v\n", err)
			os.Exit(1)
		}
	}
}
```

The delete function to clean up the error file:
```
// deleteErrorFile deletes the error file.
func deleteErrorFile() {
	if *flErrorFile != "" {
		if _, err := os.Stat(*flErrorFile); err != nil {
			if os.IsNotExist(err) {
				return
			} else {
				fmt.Fprintf(os.Stderr, "ERROR: can't check the status of the error file: %v\n", err)
				os.Exit(1)
			}
		}

		if err := os.Remove(*flErrorFile); err != nil {
			fmt.Fprintf(os.Stderr, "ERROR: can't delete the error file: %v\n", err)
			os.Exit(1)
		}
	}
}
```

**Comment by nan-yu** [comment]
FYI @janetkuo @haiyanmeng @ekitson

**Comment by haiyanmeng** [comment]
@nan-yu , the proposal misses one thing: when to clean up the error file.

**Comment by nan-yu** [comment]
> Nan Yu , the proposal misses one thing: when to clean up the error file.

Thanks for capturing it. I added a new section to the proposal.

**Comment by thockin** [comment]
I am a little unclear on WHY this matters?  What is another container going to do with this information?

**Comment by nan-yu** [comment]
> I am a little unclear on WHY this matters? What is another container going to do with this information?

The error file will be mounted to a volume, which can be shared by other containers so that they can read and return the error information to the user directly.
Otherwise, we have to ask the user to check the git-sync logs to figure out what went wrong.

**Comment by nan-yu** [comment]
One example is that Config Sync is using git-sync to fetch the git commits. If git-sync fails to sync the repository (e.g. invalid branch), the Config Sync container only sees a non-existent directory.
When Config Sync reports the error, it has to ask the user to check the git-sync logs.

With the exported error file, Config Sync can read the file and add the error information to the user-facing error in one shop.

**Comment by thockin** [comment]
So there would be no API here - no guarantees of compatibility or semantic meaning.

Do we really care about just errors that cause Exit(), or should there be a path for transient git errors (e.g. can't sync, will retry)?

**Comment by nan-yu** [comment]
> So there would be no API here - no guarantees of compatibility or semantic meaning.

Correct. There won't be further processing on the error file. Only the file content matters.

> Do we really care about just errors that cause Exit(), or should there be a path for transient git errors (e.g. can't sync, will retry)?

We are not only exporting errors that cause Exit(), but also those cause retries. See https://github.com/nan-yu/git-sync/commit/07349f6331eb588932aada982ee87cefac474359#diff-3ec698251084e7b2e19c3f03f59abb43d63a1d02610d15e8f860df56d2ccc17cR432

**Comment by ekitson** [comment]
Since git-sync is a sidecar, we want to avoid exposing it as an implementation detail to users. Our desire is just to increase visibility of error messages, so we don't need the stronger guarantees of an API. If we (or some other user of git-sync) wanted that, I would propose something like a git-sync CRD where the spec drives behavior (eg replacing the environment variables) and the status reflects errors, conditions, etc. However that seems more heavyweight than what we need.

**Comment by nan-yu** [comment]
@thockin can you revisit this proposal whenever you get a chance?

**Comment by thockin** [comment]
Hi, I'm taking a look at this but I have a question on the consumption of this new API (that's what it is).

Writing to a file and then deleting the file is sort of a weird API for consumers, isn't it?  They need to inotify or something and watch for the file to come and go.  I'm wondering if we can do better - make this easier to consume or something.

Would it make more sense for this to be a pipe or a UNIX socket or something?  For example, suppose we internally stored the last error (or 4) and listened on a UNIX socket.  When a client connects to that socket, we send the saved states (timestamped, etc).  If a client restarts, they can resume that process in the same way.

E.g.  Suppose we had:

```
type statusEvent struct {
    Status statusEventType
    Message string
}

type statusEventType string

const (
    StatusSuccess statusEventType = SUCCESS  // the repo synced successfully
    StatusSuccess statusEventType = ERROR  // the repo could not sync
)

type ringBuffer struct {
    events [4]statusEvent
    next int  
}

// func ringBuffer.insert(statusEvent)
// func ringBuffer.forEach(callback func(ev *statusEvent))

// somewhere...
var eventClients []net.Conn

// This probably should be async in case socket-sends block, which means we need mutex in the ring
func logStatusEvent(evType statusEventType, msg string) {
  // insert
  // forEach(send)
}
```

The UNIX socket here is roughly the same order of complexity as the webhook support.  More actually.  Like it or not, it's an API (even if we don't make guarantees around the content of the message).  I think it needs to be robust enough and easy enough to use that we (I) can support it long term.

Am I asking too much?

**Comment by thockin** [comment]
I just realized this doesn't work at all for startup-fail errors.  Maybe specifying this flag implies "don't exit, just sit on the UNIX socket" or maybe we need an extra flag for that?

**Comment by thockin** [comment]
To be clear - I'm not sure this is best, I just want to make sure we think about better consumer experience.  It may be that some sort of file-based thing is best

**Comment by nan-yu** [comment]
Whether we use the file-based approach or a UNIX socket depends on the motivation. For our use case, we use it more for logging purpose. 
We don’t need to monitor the file and then notify other process that git-sync fails. Instead, we just want to check the error message when we already know git-sync fails. I believe other customers might have a similar use case. They don't need to watch the file come and go, but want to check the content when they know errors occur by other means (GIT_SYNC_DEST is empty, no work tree or etc.).
I feel like UNIX socket is more for monitoring and notification purpose. It requires a client to keep monitoring the socket. If no client is monitoring, the status event will be lost. However, the error file will persist.
From the customer’s point of view, it is easier to read a file than to monitor a UNIX socket in a separate process.

If creating a file and deleting it is kind of weird. We can repurpose the file to be a **_status_** file instead of an **_error_** file. The file should always exist and we just need to overwrite it with the most recent error message or a blank content when there’s no error.

**Comment by thockin** [comment]
> we just want to check the error message when we already know git-sync fails.

How do you know it has failed?

> I believe other customers might have a similar use case. They don't need to watch the file come and go, but want to check the content when they know errors occur by other means (GIT_SYNC_DEST is empty, no work tree or etc.).

I'm mostly thinking about how a client knows that the file has new
information (or that old information is not valid any more).  Will you
poll on it and just try to read every N seconds?  How do you know the
file has been truncated or removed?

> I feel like UNIX socket is more for monitoring and notification purpose. It requires a client to keep monitoring the socket. If no client is monitoring, the status event will be lost. However, the error file will persist.
> From the customer’s point of view, it is easier to read a file than to monitor a UNIX socket in a separate process.

I was thinking of the UNIX socket as a buffered pipe - git-sync would
retain N status events and whenever you connect you would get all N
and any additional ones that show up.  That way you don't "lose"
events.  But this is really unpleasant when the error in question
causes a restart, for example.  Files are better in that regard.  The
problem is that files make a poor IPC mechanism in the face of
truncation.

> If creating a file and deleting it is kind of weird. We can repurpose the file to be a status file instead of an error file. The file should always exist and we just need to overwrite it with the most recent error message or a blank content when there’s no error.

The problem is that there's no reliable way to tell if an open file
was truncated.  It all comes down to how we expect the file to be
consumed.  Do you expect the client to read the file periodically and
get the state, or do you expect them to open it and wait for new
information?

How about something like this:

Simple design (close to what you have):

- The error file may or may not exist.
- If it exists it holds 1 status record (in a defined format).
- On success the file is removed.
- Writes to the file ALWAYS write to a tempfile, then rename that to
the status file (this ensures a different inode number).
- Clients can poll (or whatever).  They know that status has changed
when either a) the file appears; b) the file disappears; c) the inode
number changes.
- Once a client has read the file with a given inode number, it does
not have to read the file again unless the inode number changes.

More complex (not needed, I think):

- The error file is a log of N or less records (in a defined format).
- git-sync will ONLY ever append to the file or replace it with a new file.
- Changing from failed-state to success is a record.
- Clients can poll (or whatever).  If the file has the same inode
number they can read().  If the inode changes() they must close and
reopen the file.
- Git-sync will rotate the file when it hits N records, retaining 0.5
* N of them.  Write to a tempfile and rename.

The question is whether we think any client will ever need more than
the most recent status?

**Comment by nan-yu** [comment]
> How do you know it has failed?
>
> I'm mostly thinking about how a client knows that the file has new
> information (or that old information is not valid any more).  Will you
> poll on it and just try to read every N seconds?  How do you know the
> file has been truncated or removed?

We have a reconciler periodically (every 5 seconds) polls on the `--dest` directory to check if the directory can be resolved successfully. If not, we know an error occurs in the sync process and then read the error file, eventually close the file.
Basically, we are polling on `--dest` instead of the error file. 

> The problem is that there's no reliable way to tell if an open file
> was truncated.  It all comes down to how we expect the file to be
> consumed.  Do you expect the client to read the file periodically and
> get the state, or do you expect them to open it and wait for new
> information?

The client reads the file periodically to get the state and then closes the file. We will never keep the file open and waiting for new information. With that being said, do you think file truncation is still an issue?
If the open file happens to be truncated, we're mostly likely reading the latest error information.
Plus, we set `--wait` to 15 seconds, so git-sync polls on the remote git repo every 15 seconds. While the reconciler checks the `--dest` directory every 5 seconds. Even the file is truncated, it will be fixed in the next reconciliation process.

I'm okay with the simple design, just want to check if writing to a temp file and then renaming is necessary.

**Comment by thockin** [comment]
> We have a reconciler periodically (every 5 seconds) polls on the --dest directory to check if the directory can be resolved successfully. If not, we know an error occurs in the sync process and then read the error file, eventually close the file.
Basically, we are polling on --dest instead of the error file.

What happens if the directory resolves (was previously pulled and is present) but the git remote is down?  How can a client tell the difference between "no updates" and "failing to receive updates"?

> The client reads the file periodically to get the state and then closes the file. We will never keep the file open and waiting for new information. With that being said, do you think file truncation is still an issue?

If we define that as the protocol, then no - truncation should not be an issue,

> I'm okay with the simple design, just want to check if writing to a temp file and then renaming is necessary.

The rename is how you can a) guarantee atomic updates of the file (client can't read half of a message) and b) tell clients that the file has been updated, even if the contents are the same.

I'd say that atomic updates are a requirement, and inode number changing is just a side-benefit.

**Comment by nan-yu** [comment]
> What happens if the directory resolves (was previously pulled and is present) but the git remote is down? How can a client tell the difference between "no updates" and "failing to receive updates"?

I just realize the reconciler won't be able to immediately notice the difference. It sets a `--max-sync-failures`, so the `git-sync` container  keeps exiting abnormally and restarting. Eventually, the reconciler gets to an  unhealthy state.

I think you proposed a great solution to the issue. In the reconciliation stage, we could poll on both the error file and the `--dest` directory. That will capture the `failing to receive updates` error.

> I'd say that atomic updates are a requirement, and inode number changing is just a side-benefit.

Sounds good to me. I'll update the proposal and https://github.com/kubernetes/git-sync/pull/331 to reflect the change.

**Comment by nan-yu** [comment]
Both the proposal and the #331 are ready to be reviewed.

**Comment by thockin** [comment]
NOTE: let's leave this open until we port #331 to the master (v4 dev) branch
