### ISSUE TITLE
GIT_SYNC_ONE_TIME not honored

### ISSUE THREAD

**Issue by mgilbir** [kubernetes/git-sync#36]
When I set the `one-time` flag along with a revision via the `rev` flag the program goes into the `sleepForever` call on https://github.com/kubernetes/git-sync/blob/master/cmd/git-sync/main.go#L185, never reaching the test for the `one-time` flag on line 187.

Would you accept a PR on this or you prefer to tackle it yourselves?

**Comment by thockin** [comment]
PR welcome, would be nice to have a testcase for this, too!

**Comment by mgilbir** [comment]
I'm sorry for dropping the ball on this one!

I had a work around in my setup and then got swamped with other tasks :(

Thanks for fixing it!
