### ISSUE TITLE
Move the git-sync-hook executed after the symlink

### ISSUE THREAD

**Issue by yogyang** [kubernetes/git-sync#369]
Hi, guys, wonder could we move the git-sync-hook-command after the symlink.
https://github.com/kubernetes/git-sync/blob/32828834a7a0f6c77d7ffb565a071afddce536b8/cmd/git-sync/main.go#L666-L676

The scenario is I want to put some scripts in my remote repo, and I would like to execute on_release.sh when git-sync done.
So the hook command would be like `sh /{dist}/script/on_release.sh`,  with the symlink not done yet, I can not set the correct script path.

**Comment by thockin** [comment]
The exec is run in the worktree root - is that not sufficient?

Anyway, it seems like a reasonable suggestion.
