### ISSUE TITLE
Error on create and start up containers from the buildx docker image

### ISSUE THREAD

**Issue by fyudelgado** [kubernetes/git-sync#373]
I'm trying to deploy a container with the git-sync project.

I successful pass the docker buildx stage, and also create the docker images to be used on the container for the git-sync deployment.

Once I try to start up the git-sync container, I get that the container is not running and Exited with a status code 1.
On the run command when I startup the container:

```
docker run -d \
    -v /tmp/git-data:/tmp/git \
    registry/git-sync:tag \
        --repo=https://github.com/kubernetes/git-sync \
        --branch=master \
        --wait=30
```

The promp doesn't show any error, but when I use the "docker ps -a" command to show if the container was created and running. Only shows that the container was Exited with the code 1 and doesn't start.

```
CONTAINER ID   IMAGE                                   COMMAND                  CREATED          STATUS                      PORTS                  NAMES
c484f9120cdb   repository/git-sync:release__linux_amd64   "/git-sync --repo=ht…"   16 minutes ago   Exited (1) 16 minutes ago                          zealous_ritchie
a1da8bdde9e7   nginx                                   "/docker-entrypoint.…"   25 minutes ago   Up 24 minutes               0.0.0.0:8080->80/tcp   vibrant_herschel
```
Is there any step that I need to do, that is missing?

**PD**: The container with nginx that show thought the http server the content of the git repository, starts up fine.

I'm running:

- Ubuntu 20.04 LTS
- Docker CE 20.10.5
- Go version go1.16.3 linux/amd64

**Comment by thockin** [comment]
Did you look at the git-sync logs?  Try running it as `-ti` instead of `-d`
?

Try running ./test_e2e.sh?

A quick test from HEAD shows me:

```
$ docker run -ti
gcr.io/k8s-staging-git-sync/git-sync:v3.2.1-31-gb0ac361__linux_amd64 --repo=
https://github.com/kubernetes/git-sync --branch=master --wait=30
INFO: detected pid 1, running init handler
I0407 23:25:38.386603      12 main.go:437]  "level"=0 "msg"="starting up"
 "args"=["/git-sync","--repo=https://github.com/kubernetes/git-sync","--branch=master","--wait=30"]
"pid"=12
I0407 23:25:38.386654      12 main.go:701]  "level"=0 "msg"="cloning repo"
 "origin"="https://github.com/kubernetes/git-sync" "path"="/tmp/git"
I0407 23:25:40.410955      12 main.go:593]  "level"=0 "msg"="syncing git"
 "hash"="e0fe34164d119d954b8c05261aa6597b4146c2c8" "rev"="HEAD"
I0407 23:25:41.122887      12 main.go:614]  "level"=0 "msg"="adding
worktree"  "branch"="origin/master"
"path"="/tmp/git/e0fe34164d119d954b8c05261aa6597b4146c2c8"
I0407 23:25:41.274018      12 main.go:637]  "level"=0 "msg"="reset worktree
to hash"  "hash"="e0fe34164d119d954b8c05261aa6597b4146c2c8"
"path"="/tmp/git/e0fe34164d119d954b8c05261aa6597b4146c2c8"
I0407 23:25:41.274037      12 main.go:642]  "level"=0 "msg"="updating
submodules"
```

So it seems to work...

**Comment by fyudelgado** [comment]
I see that the problem is on the -v parameter that has the next values:

`-v /tmp/git-data:/tmp/git
`
On the log console using the Iteractive mode, shows the next error:

```
INFO: detected pid 1, running init handler
I0408 22:13:18.401535      12 main.go:437]  "level"=0 "msg"="starting up"  "args"=["/git-sync","--repo=https://github.com/kubernetes/git-sync","--branch=master","--wait=30"] "pid"=12
I0408 22:13:18.401631      12 main.go:701]  "level"=0 "msg"="cloning repo"  "origin"="https://github.com/kubernetes/git-sync" "path"="/tmp/git"
E0408 22:13:18.404978      12 main.go:462]  "msg"="too many failures, aborting" "error"="Run(git clone --no-checkout -b master https://github.com/kubernetes/git-sync /tmp/git): exit status 1: { stdout: \"\", stderr: \"Cloning into '/tmp/git'...\\n/tmp/git/.git: Permission denied\\n\" }"  "failCount"=0
```

It seems that the user that trying to write on the /tmp/git does not have privileges on the container. I quit this parameter on the container creation and the container runs successful.

Do you know what is wrong?

Regards,
Francisco Yu

**Comment by thockin** [comment]
Docker creates volumes as root.  git-sync does not run as root.  You have
to make the volume with the right permissions.
