### ISSUE TITLE
No url found for submodule

### ISSUE THREAD

**Issue by flvritski** [kubernetes/git-sync#374]
Hi, i'm trying to git clone a private repo, and it has init a submodule. 
I've seen that by-default GIT_SYNC_SUBMODULE is recursive, but it is still not working. I've tried it with "off" and "shallow", still no results.
I'm cloning using HTTPS.

`E0408 10:35:29.173563      15 main.go:348]  "msg"="failed to sync repo, aborting" "error"="error running command: exit status 128: \"fatal: No url found for submodule path 'k8s/plugins/mitogen' in .gitmodules\\n\""`

Could you please provide some help with this?

**Comment by thockin** [comment]
Can you help me create a reproduction case?  We have test cases around submodules that pass, and many users of it, so something is different in your setup.

https://servd.host/docs/no-url-found-for-submodule-path

**Comment by thockin** [comment]
I'm going to close this for now.  If you or anyone has a clean repro for this, I want to hear it.
