### ISSUE TITLE
Why mount volume on /tmp/git ?

### ISSUE THREAD

**Issue by kevinkirkup** [kubernetes/git-sync#382]
A couple of questions.

Why does the documentation specify mounting the git repository on `/tmp/git`?
Won't this get deleted by the file reaper periodically?
Is this in the documentation somewhere? I'm not seeing anything about it.

Thanks for you help.

**Comment by thockin** [comment]
You have to mount it SOMEWHERE.  /tmp was chosen because it's known to exist pretty much everywhere.  Inside of a container, there's no reaping (usually).  You're free to set `--root` to anything you want.
