### ISSUE TITLE
sync without project folder

### ISSUE THREAD

**Issue by aushafy** [kubernetes/git-sync#409]
Hi folks, just want to make sure that is there any parameters that we can sync without the project folder. for the example i have the repo url https://github.com/aushafy/repo-example.git so when I do git sync it would be /opt/app/repo-example/ how git sync to do this case ?

**Comment by stp-ip** [comment]
Maybe I'm misunderstanding, but did you try `--dest`?

**Comment by aushafy** [comment]
I'll try

**Comment by aushafy** [comment]
solve with --dest parameter, thanks
