### ISSUE TITLE
Allow `--dest` to not be nested under `--root`

### ISSUE THREAD

**Issue by thesuperzapper** [kubernetes/git-sync#428]
I have a use-case where I need to store the main `--dest` symlink in a folder which is not under `--root`, as the application consuming the repo will be confused by multiple folders.

For example, the folder structure might look like:
```
# GIT_SYNC_ROOT=/tmp/git
/tmp/git/SHAXXXX
/tmp/git/SHAXXXX

# GIT_SYNC_DEST= /home/repos/repo1
/home/repos/repo1
```

**Comment by thesuperzapper** [comment]
@thockin what are your thoughts?

**Comment by stp-ip** [comment]
Within Kubernetes my initial thought would be to mount a subpath as a separate directory. Basically creating the separation without doing it with git-sync itself.

**Comment by thockin** [comment]
Unfortunately, subpath does not play nicely with symlinks (bindmounts
resolvethe link).

I'm not hard AGAINST this, but it changes the used of readlink() as an API
to know the current commit.  Will need to update those docs and maybe save
it for the v4 branch?  Not sure - it is strictly a breaking change.

**Comment by stp-ip** [comment]
It does seem like not something Git-sync should do, but I might see why it might be useful. If done v4 only seems good.

**Comment by thockin** [comment]
The `readlink()` behavior is not really documented, so changing it to `basename(readlink())` doesn't seem SO egregious.

As I said, I am not hard against this.  I'll leave it open, but it's not my priority right now.  I am trying to get the v4 overhaul mergeable.

**Comment by janarthanandev** [comment]
is there any update?
@thesuperzapper could you able to achieve with any workaround.

**Comment by thockin** [comment]
I have not had time to work on this yet.
