### ISSUE TITLE
Add flag `--password-file`

### ISSUE THREAD

**Issue by zhouhaibing089** [kubernetes/git-sync#429]
The documentation says:

GIT_SYNC_PASSWORD | --password | the password or personal access token to use for git auth. (users should prefer env vars for passwords) | ""
-- | -- | -- | --

I think it is not preferred to use ENV to pass passwords. This is mentioned in [CIS benchmarks][1]:

> 5.4.1 | Prefer using secrets as files over secrets as environment variables

Instead, we could probably do the same as `--ssh-key-file` and add a similar flag `--password-file` so the program can read password from a file volume.

[1]: https://cloud.google.com/kubernetes-engine/docs/concepts/cis-benchmarks

**Comment by thockin** [comment]
See https://github.com/kubernetes/git-sync/pull/254

The docs are correct until we have a from-file option - file >> env >> CLI.  :)

**Comment by zhouhaibing089** [comment]
Oops, I checked existing issues, but not pull requests before filing this issue.

**Comment by stp-ip** [comment]
Seems merged so closing. If anything still needs to be done, please reopen or file a new issue.
