### ISSUE TITLE
is git-sync copying files as a root user?

### ISSUE THREAD

**Issue by VikramTiwari** [kubernetes/git-sync#43]
If this is true then `git-sync` cannot be used for the static-file based server along with nginx.

- git-sync copies files as a root user in a volume
- If I attach that volume to nginx then it gives 403 forbidden error

Could there be any other issue for this behaviour?

**Comment by thockin** [comment]
Run git-sync as non-root, or set the gsGID ?

**Comment by VikramTiwari** [comment]
@thockin Yes, that is doable. But, shouldn't that be the default? Can't think of a reason why files should be copied as root.

**Comment by thockin** [comment]
We don't know what UID to run as unless you tell it...

**Comment by VikramTiwari** [comment]
Ah! That makes sense. Will try and confirm if it works.

**Comment by stp-ip** [comment]
This is mostly a duplicate of #38.

Documentation for workarounds or a default fix will be added as part f #38.
