### ISSUE TITLE
Trouble Using Container Successfully

### ISSUE THREAD

**Issue by chriscardillo** [kubernetes/git-sync#438]
Hi,

Thanks for this awesome utility, unfortunately I am having trouble getting it to work.

I have a private repository I am trying to sync with.

I have a secret, `github-creds` with my `username` and a Github PAT as my `password`. I have confirmed the secrets are correct in the cluster.

The error I receive is:

```
│ INFO: detected pid 1, running init handler                                                                                                                                                                      │
│ I0802 21:41:06.955321      12 main.go:507] "level"=0 "msg"="starting up" "pid"=12 "args"=["/git-sync"]                                                                                                          │
│ I0802 21:41:06.955402      12 main.go:860] "level"=0 "msg"="cloning repo" "origin"="https://github.com/chriscardillo/super-private-repo" "path"="/tmp/git"                                                          │
│ E0802 21:41:07.101125      12 main.go:172] "msg"="too many failures, aborting" "error"="Run(git clone --no-checkout -b main https://github.com/chriscardillo/super-private-repo /tmp/git): exit status 128: { stdou │
│ t: "", stderr: "Cloning into '/tmp/git'...\nfatal: could not read Username for 'https://github.com': No such device or address\n" }" "failCount"=0                                                              │

```

Am I missing something? Thanks in advance for your help here. Manifest below.

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: git-sync-test
spec:
  replicas: 1
  selector:
    matchLabels:
      name: git-sync-test
  template:
    metadata:
      labels:
        name: git-sync-test
    spec:
      containers:
      - name: git-sync
        image: k8s.gcr.io/git-sync/git-sync:v3.3.4
        volumeMounts:
        - name: shared-sync
          mountPath: /tmp/git
        env:
        - name: GIT_SYNC_REPO
          value: https://github.com/chriscardillo/super-private-repo
        - name: GIT_SYNC_BRANCH
          value: main
        - name: GIT_SYNC_DEST
          value: git-sync
        - name: GIT_SYNC_USERNAME
          valueFrom:
            secretKeyRef:
              name: github-creds
              key: username
        - name: GIT_SYNC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: github-creds
              key: password
        - name: GIT_SYNC_WAIT
          value: "15"
      volumes:
      - name: shared-sync
        emptyDir: {}
```

**Comment by thockin** [comment]
If you set the `command` to `[ "sh", "-c", "sleep 100000" ]` and then
``kubectl exec` a shell into it, is the password vsr being set properly?  I
have to admit that the username and password args are not super well tested
(most people use SSH).

"No such device" makes it sound like a TTY problem.

Can you maybe repro locally without k8s?  e.g.

```
docker run -ti \
    -e GIT_SYNC_REPO=https://github.com/chriscardillo/super-private-repo \
    -e GIT_SYNC_BRANCH=main \
    -e GIT_SYNC_DEST=git-sync \
    -e GIT_SYNC_USERNAME=<username> \
    -e GIT_SYNC_PASSWORD=<password> \
    -e GIT_SYNC_WAIT="15" \
    k8s.gcr.io/git-sync/git-sync:v3.3.4
```

Then maybe without the -ti and check the logs?

**Comment by chriscardillo** [comment]
Went ahead and tried three things in the cluster:

- Ran the container with the command `[ "sh", "-c", "sleep infinity" ]` and username/password vars coming from my secret. 
    - Confirmed all `GIT_SYNC_` env vars made it into the container, including username and password.
- Ran the container with its default command, with the username and password env vars as plain text.
    - Everything works and I am able to sync.
- Ran the container with its default command, with the username and password being pulled in via secrets (as in my example above)
    - I receive the error about `could not read Username for 'https://github.com': No such device or address`

Is it possible that, for some reason, the container is trying to use SSH instead of username/password in the third example? FWIW - I am using a Github PAT in the third example instead of a password, which ought to bypass the need for any user input.

**Comment by chriscardillo** [comment]
@thockin thanks so much for your help - I made a silly mistake.

There was a new line at the end of my secrets. Everything works fine. Thank you and sorry for the inconvenience.

**Comment by thockin** [comment]
Glad it worked out.  I am working on a better username/password
testcase anyway :)

**Comment by chriscardillo** [comment]
Thanks :)

Hey - while I've got you. For a separate container that takes advantage of the git-sync sidecar, I've noticed if I try to use a `subPath`, the git-sync doesn't properly sync. Does that make sense? I ran into it today.

**Comment by thockin** [comment]
SubPath works through symlinks and bind mounting a symlink binds the thing
it points to rather than the link (that's just how the kernel works). A git
update makes a new file, which means the bind mount doesn't get updated and
still points to the old.

It kind of sucks, but I don't have an answer.
