### ISSUE TITLE
Is there a way to use Github App Access Token with git sync?

### ISSUE THREAD

**Issue by cfraleig** [kubernetes/git-sync#450]
We have some security concerns with using ssh and/or personal access token to authenticate git-sync with github. Is there a way we can auth using a github app?

**Comment by thockin** [comment]
I have no notion of how that would work.  I'm not inherently against it, but I'd need someone (you?) to detail how exactly it would work.  How would you configure git to do this?

**Comment by yiga2** [comment]
https://docs.github.com/en/developers/overview/managing-deploy-keys#server-to-server-tokens describes the steps to setup and authenticate with a GitHub App.
However, if anyone is concerned about using personal SSH keys, look at `Deploy keys` instead, in the same webpage/link

**Comment by joebowbeer** [comment]
@thockin I'm looking for this as well.

This was not completed, right? That is, there is no way to auth with a GitHub App? (e.g., like ArgoCD does)

If not, should I reopen this or create a new issue?

**Comment by thockin** [comment]
It aged out.  I don't really know enough about github apps to know what this would mean.  I am not against it in principle, I just haven't any idea how to do what OP wanted.  Happy to discuss if someone can bring information.
