### ISSUE TITLE
Any way to use git-sync with AWS CodeCommit?

### ISSUE THREAD

**Issue by sramek5** [kubernetes/git-sync#456]
The problem is, you need to use the config file like this:
```
Host git-codecommit.*.amazonaws.com
User Your-SSH-Key-ID, such as APKAEIBAERJR2EXAMPLE
IdentityFile Your-Private-Key-File, such as ~/.ssh/codecommit_rsa or ~/.ssh/id_rsa
         
```
and store it in ```~/.ssh/config```.

I tried to store it in ```/etc/git-secret/config``` and also in ```~/.ssh/config``` without success.

Documentation: https://docs.aws.amazon.com/codecommit/latest/userguide/setting-up-without-cli.html

Any advice please?

**Comment by sramek5** [comment]
Manually (executed in running container and tried to git clone) it works, when the ```config``` file with description is mounted at ```/tmp/.ssh/config```.

Unfortunately, the pod is still in CrashLoop state.

Logs:
```
INFO: detected pid 1, running init handler
I1128 13:06:32.503565      14 main.go:454] "level"=0 "msg"="starting up" "pid"=14 "args"=["/git-sync"]
I1128 13:06:32.503726      14 main.go:822] "level"=0 "msg"="cloning repo" "origin"="ssh://git-codecommit.eu-central-1.amazonaws.com/v1/repos/<repo-path>" "path"="/tmp/git"
E1128 13:06:32.635338      14 main.go:504] "msg"="too many failures, aborting" "error"="Run(git clone --no-checkout -b master ssh://git-codecommit.eu-central-1.amazonaws.com/v1/repos/<repo-path> /tmp/git): exit status 128: { stdout: "", stderr: "Cloning into '/tmp/git'...\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n" }" "failCount"=0
```

**Comment by sramek5** [comment]
Finally I found a solution!

I put ```config``` file:
```
Host git-codecommit.*.amazonaws.com
User <ssh-ID-from-AWS>
```
Into ```/tmp/.ssh/config``` path. 
Purposly I did not specify ```IdentityFile``` (path to ssh key), path is taken automatically.
And env ```GIT_KNOWN_HOSTS``` I changed to ```"false"```.

Now it clones repo from CodeCommit using SSH.

**Comment by thockin** [comment]
Glad to hear this works.  I was just thinking about how best to dig into it.
