### ISSUE TITLE
AzureFile Share  mount issue

### ISSUE THREAD

**Issue by raefezzeldin** [kubernetes/git-sync#457]
When I try to mount AzureFileShare on git-sync image this error appears to me 

bad option; for several filesystems (e.g. nfs, cifs) you might need a /sbin/mount.<type> helper program.

**Comment by thockin** [comment]
Can you provide more details?  Exactly what did you do?  Git-sync doesn't
have a "mount" function - do you mean with docker? Or with kubernetes?
Where is that error logged?  What was the exact git-sync command line?

**Comment by raefezzeldin** [comment]
I am using git sync as an init container to load files from git repos. Airflow helm chart , what i am trying to do is persisting the files onto a mount share using Azure file share. So git sync container should get the files and write to the mounted volume.

Check below the error appears to me. And the storage class I am using to mount azure fileshare on git sync init container.


I have tried to use AzureFileShare. but I am facing an issue in git-sync-init container (Scheduler)

MountVolume.SetUp failed for volume "pv-airflowdags" : mount failed: exit status 32 Mounting command: mount Mounting arguments: -t cifs -o file_mode=0777,dir_mode=0777,vers=3.0,gid=0,actimeo=30,mfsymlinks,<masked> //tpaydatasa.file.core.windows.net/fs-airflowdags /var/lib/kubelet/pods/xxxx/volumes/kubernetes.io~azure-file/pv-airflowdags Output: mount: /var/lib/kubelet/pods/xxx/volumes/kubernetes.io~azure-file/pv-airflowdags: bad option; for several filesystems (e.g. nfs, cifs) you might need a /sbin/mount.<type> helper program.

this is the storage class I have created

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: my-azurefile
provisioner: kubernetes.io/azure-file
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=0
  - gid=0
  - mfsymlinks
  - cache=strict
  - actimeo=30
parameters:
  skuName: Premium_LRS

**Comment by thockin** [comment]
This has nothing to do with git-sync - it's really about how to use Azure
mounts in Kubernetes.

Sorry to not be helpful, but this repo can only field issues with git-sync
itself.  You should move to this to the Kubernetes repo (if you think it is
a bug) or more likely to one of the support forums - StackOverflow,
Discuss, Slack etc.
