### ISSUE TITLE
Can it be added to show the speed and process of pulling the git repository

### ISSUE THREAD

**Issue by ilanni2460** [kubernetes/git-sync#458]
Can it be added to show the speed and process of pulling the git repository

**Comment by thockin** [comment]
Hi,

Unfortunately git-sync internally executes `git`, which doesn't really have a friendly way to extract progress (that I know of)  other than running it async, and reading stderr and splitting on carriage-return (which would produce a lot of logs).

I don't think it's worth the effort.  If there was something friendlier (like "emit one message every 5 seconds") maybe?
