### ISSUE TITLE
--password required even when using --ssh-key-file

### ISSUE THREAD

**Issue by hterik** [kubernetes/git-sync#467]
Config:
```
GIT_SYNC_USERNAME: "myuser"
GIT_SSH_KEY_FILE: "/blabla/id_rsa"
```
Leads to following error when starting git-sync 3.3.5.
`ERROR: --password or --password-file must be set when --username is specified`

If i'm not mistaken this should be a valid configuration, setting the ssh username and ssh authentication. 
This was not a problem with 3.3.0

**Comment by thockin** [comment]
Indeed some logic changed here.

**Comment by thockin** [comment]
What  are you specifying as `--repo` ?  I don't see how specifying `--username` is possible with an SSH repo, which demands `user@repo/path` syntax

**Comment by hterik** [comment]
The repo is just ssh://address, without user, but i also have .ssh/config where that address maps to specific user.
Should I remove GIT_SYNC_USERNAME entirely? Seems like it would not be used in ssh case anyway like you say.

**Comment by thockin** [comment]
yes, I think previously we tolerated it, but it was meaningless.  At some point we added better cross-flag checking, and it caught you. :)
