### ISSUE TITLE
Option for executing webhook only after successful exechook

### ISSUE THREAD

**Issue by DmitriySafronov** [kubernetes/git-sync#481]
Is there any chance to implement such option?

My workflow:
1) sync config from git
2) rsync changes to config volume
3) execute webhook to restart web-app with new rsync'ed config

Now I've get a race condition if webhook & exechook are executed simultaneously

**Comment by thockin** [comment]
That's not a very exciting proposal, honestly.   Because if you want it one
way, someone else wants it differently.  Can you send the webhook from your
exechook yourself?

**Comment by DmitriySafronov** [comment]
I've rewritten my script to avoid race contdition. Now I use only exechook + rsync & curl.
