### ISSUE TITLE
readinessProbe/livenessProbe (k8s) fails if the pod has restarted and there is no change in git repo

### ISSUE THREAD

**Issue by matan-aharonov** [kubernetes/git-sync#488]
**Scenario:**
The pod is up and a successful clone to git repo has been performed. 
At some point the pod restarts and there is no change in the git repo, in this case the git-sync is not ready and the whole pod is considered not ready (especially in the situation that it runs as a sidecar and causes the whole pod to be not ready).

**The problem is in the next section of the code:**
The call to **setRepoReady** is performed in the following function -**addWorktreeAndSwap**. 
The call to the **addWorktreeAndSwap** function is performed in the **syncRepo** function. 
But we do not call **addWorktreeAndSwap** if the following condition is met, and immediately exit the function:

```
	default:
		// Not the first time. Figure out if the ref has changed.
		local, remote, err := getRevs(ctx, dest, branch, rev)
		if err != nil {
			return false, "", err
		}
		if local == remote {
			log.V(1).Info("no update required", "rev", rev, "local", local, "remote", remote)
			return false, "", nil
		}
		log.V(0).Info("update required", "rev", rev, "local", local, "remote", remote)
		hash = remote
```

The problem with this condition: **local == remote**. 
If this condition is met then it should be announced that the repo is also ready, because otherwise it will not be ready until the next clone...

**Comment by thockin** [comment]
That sounds legit.  PRs welcome or I can get to it when I get to it.

**Comment by thockin** [comment]
Fix seems easy, working on a test case
