### ISSUE TITLE
SubPath Directory Sync

### ISSUE THREAD

**Issue by caxefaizan** [kubernetes/git-sync#507]
I have used git-sync in airflow where we can provide the subpath from where only a specific directory is synced. But I dont see that option here. Lets say i have a repo where there is a folder
dags/
    - active/example1.py
    - archive/example2.py
 i want only the active folder to be synced 
```
          - name: GIT_SYNC_REPO
            value: "git@gitlab.com:username/repo.git"
          - name: GIT_SYNC_ROOT
            value: "/dags/active"
          - name: GIT_SYNC_REV
            value: "HEAD"
          - name: GIT_SYNC_DEST
            value: "dags"
```
But this doesnt seem to work. It sync both the folders.
{ stdout: "", stderr: "Cloning into '/dags/active'...\nFailed to add the ECDSA host key for IP address ' x.x.x.x' to the list of known hosts (/etc/git-secret/known_hosts).\r\nBUG: refs/files-backend.c:2953: initial ref transaction called with existing refs\n" }" "failCount"=0

**Comment by thockin** [comment]
Sorry, help me understand wnat you want?  You want to sync a repo but only check out some of the contents?

Does the `--sparse-checkout-file` flag help?

Other than that, I don't know how to ask git to only clone part of a repo...

**Comment by caxefaizan** [comment]
I see. Git-Sync doesn't allow us to sync  a particular directory. The error was coming up because i was running two gitsync container and mounting on the same destination directory. My Bad

**Comment by thockin** [comment]
Well, a sparse-checkout is KIND OF what you asked for..

**Comment by caxefaizan** [comment]
so you mean sparse checkout will only sync a particaular folder in the repo?

**Comment by thockin** [comment]
I'm not sure what it does "on the wire" honestly, but it will only present
the items listed in the file.

**Comment by caxefaizan** [comment]
I'm sorry but for sparse checkout do i have to mention the directory "/dags/active" ?

**Comment by thockin** [comment]
Git-sync uses git's spec for this.

https://git-scm.com/docs/git-sparse-checkout

**Comment by AndrewOYLK** [comment]
I met "no such file or directory" problem too. How do we configure this parameter "GIT_SYNC_SPARSE_CHECKOUT_FILE".
