### ISSUE TITLE
Slack incoming webhooks payload issue

### ISSUE THREAD

**Issue by mrc-rius** [kubernetes/git-sync#508]
Slack disabled the url of an incoming webhook because it was publicly exposed in github. The project is private but anyways they detected it and disabled the webhook and send us an email.

The issue is related with the already solved [issue here](https://github.com/kubernetes/git-sync/issues/492).

As `GIT_SYNC_EXECHOOK_COMMAND` doesn't allow parameters I can't setup the incoming webhook url as a parameter, so I have to harcode it in the sh file that I created.

Something like:

`#!/bin/sh
SHA=$(git rev-parse HEAD)
curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"Airflow code was updated to git commit $SHA\"}" $1`

where `$1` has to be changed to the url.

I tried setting up: `GIT_SYNC_EXECHOOK_COMMAND=/tmp/git/airflow/git-sync-webhook.sh https://hooks.slack.com/services/XX/XX/XX`.
But the log returns:

`I0317 12:12:10.307832      12 exechook.go:68] "level"=0 "msg"="running exechook" "command"="/tmp/git/airflow/git-sync-webhook.sh" "timeout"=30000000000`
`E0317 12:12:10.326114      12 hook.go:136] "msg"="hook failed" "error"="Run(/tmp/git/airflow/git-sync-webhook.sh ): exit status 2: { stdout: "", stderr: "curl: no URL specified!\ncurl: try 'curl --help' or 'curl --manual' for more information\n" }"`

So the url is not received in the git-sync code and then we are forced to harcode it, running the risk that in sometime the webhook gets disabled again by slack.

Any way to solve that that I didn't think about it?

**Comment by thockin** [comment]
What a weird policy - security thru obscurity, I guess.

Revisiting and extending #492: options:

1. add curl to the git-sync image, let you use exechook to call curl
2. tell you to build your own image FROM git-sync's image
3. add a `--webhook-header="key: value"` flag and a `--webhook-payload='{ "text": "${HASH}" }'` flag with variable interpolation for (at least) the current hash.
4. ??

Option 1 is bad.  You tried option 2.  Option 3 remains possible.  Option 4 could be to add a `--exechook-env="key=value"` or even just `--exechook-env="key"` (pull the value from the inherited env).  That's less complicated than Option 3, probably.

**Comment by mrc-rius** [comment]
So I guess solution is to wait until option 3 or option 4 are created in the project?

**Comment by thockin** [comment]
Or you can try making a PR :)

**Comment by mrc-rius** [comment]
will try to manage, but can't ensure will have time.

The point regarding this is `--webhook-header="key: value"` will be key as parameter name for the sh file?

In my case: `--webhook-header="url: https://hooks.slack.com/services/XX/XX/XX"` or i am not understanding it?

**Comment by thockin** [comment]
I imagined webhook-header and HTTP headers - just fed into the HTTP library

**Comment by thockin** [comment]
If you feel so inclined, #515 is a simnple patch - care to try it?

**Comment by mrc-rius** [comment]
Yes of course but I do not understand how I shoul test it?
Currently I am using as a base image: `k8s.gcr.io/git-sync/git-sync:v3.4.0`

Which image should I use in order to test it as its a PR yet?

On the other hand, will test next week as this weekend i'm no available.

**Comment by thockin** [comment]
@mrc-rius Did you have a chance to test this?

**Comment by mrc-rius** [comment]
@thockin not yet, will do it next week probably

**Comment by thockin** [comment]
The way it is currently laid out you'd set `--exechook-env=MY_SLACK_URL` and when you run git-sync you'd set the env var `MY_SLACK_URL="https://hooks.slack.com/services/XX/XX/XX"` (e.g. with `docker run -e ...` or Kubernetes `Pod.spec.containers[].env`).

Al alternate design would be to set `--exechook-env=MY_SLACK_URL="https://hooks.slack.com/services/XX/XX/XX"` - I didn't know if that was more or less useful, which is the feedback I seek.

**Comment by thockin** [comment]
hi @mrc-rius - any updates here?

**Comment by mrc-rius** [comment]
Hi @thockin,

sorry for the delay, have been out for some time.
I just tested and not working, probably some mistake in my setup, but i want to share in order to avoid multiple wrong tries:

My git-sync image dockerfile is:

```
FROM gcr.io/k8s-staging-git-sync/git-sync:v3.4.0-33-gabb90a6-dirty
#Install curl in order to be able to call Slack Webhook.
#Git-sync doesn't have curl by default and doesn't allow payloads in the calls. So it's not working without curl.
USER root
RUN apt-get update && apt-get install -y curl
```

Environment variables:

```
environment : [
          {
            name : "GIT_SYNC_BRANCH",
            value : "master"
          },
          {
            name : "GIT_SYNC_DEST",
            value : "airflow"
          },
          {
            name : "GIT_SYNC_ROOT",
            value : "/tmp/git"
          },
          {
            name : "GIT_SYNC_PERMISSIONS",
            value : "0755"
          },
          {
            name : "GIT_SYNC_DEPTH",
            value : "1000"
          },
          {
            name : "GIT_SYNC_TIMEOUT",
            value : "1200"
          },
          {
            name : "GIT_SYNC_MAX_SYNC_FAILURES",
            value : "3"
          }
        ],
        secrets : [
          {
            name : "GIT_SYNC_REPO",
            valueFrom : "${aws_ssm_parameter.airflow_git_sync_repo.arn}"
          },
          {
            name : "GIT_SYNC_EXECHOOK_COMMAND",
            valueFrom : "${aws_ssm_parameter.airflow_slack_payload.arn}"
          },
          {
            name : "MY_SLACK_URL",
            valueFrom : "/pro/airflow_env/slack_url"
          }
```

`GIT_SYNC_EXECHOOK_COMMAND` value is an sh file that has:

```
#!/bin/sh
SHA=$(git rev-parse HEAD)
curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"Airflow code was updated to git commit $SHA\"}"
```

The previous and working version had the `slack url` in the `GIT_SYNC_EXECHOOK_COMMAND` file.
`MY_SLACK_URL` value is `https://hooks.slack.com/services/XXXX/XXX/XXX`

The error i get is:

`E0425 08:06:50.411132      12 hook.go:136] "msg"="hook failed" "error"="Run(/tmp/git/airflow/git-sync-webhook.sh ): exit status 2: { stdout: "", stderr: "curl: no URL specified!\ncurl: try 'curl --help' or 'curl --manual' for more information" }"`

Probably is that it's not just delete url from sh file running in `GIT_SYNC_EXECHOOK_COMMAND` and move to `MY_SLACK_URL`.

**Comment by thockin** [comment]
You need to also use the flag `--exechook-env=MY_SLACK_URL` or the env `GIT_SYNC_EXECHOOK_ENV` to "MY_SLACK_URL".

That tells git-sync to extract the variable "MY_SLACK_URL" and pass it down to the exechook.

What I am trying to figure out is if that is too draconian - should I just export the whole env?

**Comment by mrc-rius** [comment]
Still not working.

I'm using the docker base image you updated.
And setting: 

```
          {
            name : "GIT_SYNC_EXECHOOK_COMMAND",
            valueFrom : aws_ssm_parameter.airflow_slack_payload.arn
          },
          {
            name : "GIT_SYNC_EXECHOOK_ENV"
            valueFrom : aws_ssm_parameter.slack_url_dataops.arn
          }
```

The error is:

```
2022-04-28T11:05:28.790+02:00
E0428 09:05:28.790474      13 hook.go:136] "msg"="hook failed" "error"="Run(/tmp/git/airflow/git-sync-webhook.sh ): exit status 2: { stdout: "", stderr: "curl: no URL specified!\ncurl: try 'curl --help' or 'curl --manual' for more information" }"
```

Seems like is not able to append the curl call that is done in the sh script that runs in `GIT_SYNC_EXECHOOK_COMMAND` to the url value in `GIT_SYNC_EXECHOOK_ENV`.

Values are:
`GIT_SYNC_EXECHOOK_COMMAND = /tmp/git/airflow/git-sync-webhook.sh`
Content in the file is:

```
#!/bin/sh

SHA=$(git rev-parse HEAD)

curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"Airflow code was updated to git commit $SHA\"}" https://hooks.slack.com/services/AAA/BBB/CCC
```
That last part (the one with the url) is the one I delete when failing in order to use `GIT_SYNC_EXECHOOK_ENV`

`GIT_SYNC_EXECHOOK_ENV=https://hooks.slack.com/services/AAA/BBB/CCC`

When just adding that url to the sh script everything working even using the new base image.

**Comment by thockin** [comment]
Sorry, it's obviously not clear enough. :)

> GIT_SYNC_EXECHOOK_ENV=https://hooks.slack.com/services/AAA/BBB/CCC

This new variable is intended to be an indirection.  You want to do:

MY_SLACK_URL=https://hooks.slack.com/services/AAA/BBB/CCC
GIT_SYNC_EXECHOOK_ENV=MY_SLACK_URL

This tells git-sync to pass-thru the MY_SLACK_URL variable.  Since it's so complex to explain, I'm thinking maybe it's just a bad design.  What if I just pass-thru the whole environment?

**Comment by mrc-rius** [comment]
Will test it tomorrow. Now if I only do `MY_SLACK_URL=https://hooks.slack.com/services/AAA/BBB/CCC` should work? No need to do `GIT_SYNC_EXECHOOK_ENV=MY_SLACK_URL`.

How does `GIT_SYNC_EXECHOOK_ENV` understant that the url is at `MY_SLACK_URL`, now without the redirect?

**Comment by thockin** [comment]
GIT_SYNC_EXECHOOK_ENV goes away entirely. This change makes the entire env
available to exechook commands - no special config needed.  If you set an
env-var in your pod, the exechook will see it.

**Comment by mrc-rius** [comment]
Done, is working! Thanks for the fix @thockin !

How can I receive a notification when you add this fix to prod image. Now I have it with `gcr.io/k8s-staging-git-sync/git-sync:v3.5.0-2-g8a606fa`

**Comment by thockin** [comment]
Cool.  I am not sure when I will have a moment, with KubeCon next week.  It
might be after that.

**Comment by mrc-rius** [comment]
Okay, don't worry, thats great! Thanks!
