### ISSUE TITLE
Access denied error

### ISSUE THREAD

**Issue by phspies** [kubernetes/git-sync#516]
Trying to use git-sync as a init container to clone a repository before a build process and it seems the closing process works but the symlink git creates has a problem. When trying to access the folder via the Symlink, I get a access denied.

```
root@computeplaform-build-7gsxs:/# cd code/
root@computeplaform-build-7gsxs:/code# ls -la
total 0
drwxrwxrwt  4 root  root  100 Mar 22 19:49 .
drwxr-xr-x  1 root  root   40 Mar 22 19:49 ..
drwxr-xr-x  9 65533 65533 280 Mar 22 19:49 .git
drwxr-xr-x 13 65533 65533 480 Mar 22 19:49 99aaeec3230f2e5260c82be53a50e36ab0872956
lrwxrwxrwx  1 65533 65533  40 Mar 22 19:49 prinubes.git -> 99aaeec3230f2e5260c82be53a50e36ab0872956
root@computeplaform-build-7gsxs:/code# cd prinubes.git 
bash: cd: prinubes.git: Permission denied
```
Accessing the folder directly or removing and recreating the symlink, seems to fix the problem. Any ideas why the symlink created by the clone process is broken?

```
root@computeplaform-build-7gsxs:/code# cd 99aaeec3230f2e5260c82be53a50e36ab0872956/
root@computeplaform-build-7gsxs:/code/99aaeec3230f2e5260c82be53a50e36ab0872956# ls
AppUtil  ComputePlatformWorker	LICENSE   PlatformWorker  Readme.md	UI	     common		    docker-compose.override.yml  identity
Common	 Identity		Platform  Properties	  SetEVars.bat	UnitTesting  docker-compose.dcproj  docker-compose.yml		 prinubes.sln
root@computeplaform-build-7gsxs:/code/99aaeec3230f2e5260c82be53a50e36ab0872956# cd ..
root@computeplaform-build-7gsxs:/code# rm prinubes.git 
root@computeplaform-build-7gsxs:/code# ln -s 99aaeec3230f2e5260c82be53a50e36ab0872956 prinubes 
root@computeplaform-build-7gsxs:/code# cd prinubes
root@computeplaform-build-7gsxs:/code/prinubes# ls  
AppUtil  ComputePlatformWorker	LICENSE   PlatformWorker  Readme.md	UI	     common		    docker-compose.override.yml  identity
Common	 Identity		Platform  Properties	  SetEVars.bat	UnitTesting  docker-compose.dcproj  docker-compose.yml		 prinubes.sln
```

**Comment by thockin** [comment]
That's super weird.  What storage is underneath this?  Is it NFS or SMB or something that could be weird?

Are you using seccomp or selinux?

I can't fathom anything else what would yield a "permission denied".

**Comment by phspies** [comment]
I'm using a memory volume. In terms of the seccomp or selinux, I'm using nothing. I can delete the symlink and recreate it but the link created by the clone process is unusable.

```
    volumes:
    - name: prinubes
      emptyDir:
        medium: Memory
```

**Comment by thockin** [comment]
how on earth can you get EPERM on a symlink?  I have no idea what to even
ASK to debug that.  git-sync literally exec()s "ln -s"

**Comment by thockin** [comment]
What OS is this?  What distro and kernel?

**Comment by phspies** [comment]
I just created a new image from a fresh repository pull. Docker image was created on Ubuntu 21.10. The docker image can be found here: silmaril212/git-sync:v3.5.0__linux_amd64

**Comment by thockin** [comment]
Can you repro with k8s.gcr.io/git-sync/git-sync:v3.5.0 ?

Is it under kubernetes or just `docker run` ?

**Comment by phspies** [comment]
Kubernetes, more specifically a microk8s cluster.

**Comment by thockin** [comment]
I ... can not reproduce this on a real cluster, and I would expect my head
to be bitten off if it was wide-spread.  But more than that, I can not
fathom what's CAUSING it.

can you `lsattr` the "bad" link and then the "good" one?

**Comment by phspies** [comment]
Seems to be having an issue:

```
root@computeplaform-build-9zgrs:/code# lsattr prinubes.git 
lsattr: Operation not supported While reading flags on prinubes.git
```

But then again "lsattr" doesn't work for the working link either:

```
root@computeplaform-build-9zgrs:/code/prinubes# cd ..
root@computeplaform-build-9zgrs:/code# lsattr prinubes
lsattr: Operation not supported While reading flags on prinubes
```

**Comment by phspies** [comment]
I replaced the memory volume with a local mountpoint and it seems to be working now. Not sure why the memory volume doesn't play nicely with this code.

**Comment by thockin** [comment]
I'll try that specific case.  Will make my e2e harder...

**Comment by prometheanfire** [comment]
memory volume is tmpfs, which tends to restrict symlinks a bit via the `fs.protected_symlinks` sysctl.

**Comment by thockin** [comment]
Interesting - I did not know that one.

https://sysctl-explorer.net/fs/protected_symlinks/

I can't seem to force a repro, still.  Is there an example of how to
trigger that failure?  My attempts to manually fail have failed...
