### ISSUE TITLE
Add retry loop for callGitAskPassURL

### ISSUE THREAD

**Issue by nan-yu** [kubernetes/git-sync#520]
`git-sync` [populates the Git credentials](https://github.com/kubernetes/git-sync/blob/release-3.x/cmd/git-sync/main.go#L417) outside the [retry loop](https://github.com/kubernetes/git-sync/blob/release-3.x/cmd/git-sync/main.go#L518). If the GIT_ASKPASS URL is not ready to provide the credentials initially, `git-sync` will fail with the following error:
```
calling GIT_ASKPASS URL to get credentials
failed to call ASKPASS callback URL: can't access auth URL: Get "http://localhost:9102/git_askpass" dial tcp 127.0.0.1:9102: connect: connection refused
```

To fix the failure, it needs another retry loop to get the Git credentials.

**Comment by thockin** [comment]
We also call it at the top of syncRepo: https://github.com/kubernetes/git-sync/blob/release-3.x/cmd/git-sync/main.go#L1032-L1040

Ao this initial fetch may be pointless?

**Comment by nan-yu** [comment]
Maybe remove the initial fetch because if the initial fetch fails, it exits with an error.

**Comment by thockin** [comment]
If the syncRepo one fails, the user still has to set the retries, I
guess?  I have not tried it.

PRs welcome, ideally with tests :)

**Comment by nan-yu** [comment]
I think it still needs to set creds for retries. It doesn't matter if the creds are the same since `setupGitAuth` sets the credentials globally. But in case it changes, the git auth needs to be updated.

Will start a PR with tests.

**Comment by thockin** [comment]
I have a test in my working tree, will PR eventually

**Comment by thockin** [comment]
We no longer try to get the password at git-sync startup.  We now try it at the top of each sync loop, and if it fails we count it as a sync failure (subject to --max-sync-failures).

Is that what you need?  That's how I understood it, at least :)
