### ISSUE TITLE
Not able to point to a Hash keeps giving error

### ISSUE THREAD

**Issue by ajasingh** [kubernetes/git-sync#523]
I want to pull only particular hash from git-sync but i keep getting error even the hash is present in that repo.
E0605 10:24:11.286772      12 main.go:754] "msg"="can't resolve commit, will retry" "error"="Run(git cat-file -t ): exit status 128: { stdout: "", stderr: "fatal: Not a valid object name" }" "rev"="*********" "hash"=""

I am passing args like this 
"--rev=***********",

is there something that I am doing wrong ?

**Comment by thockin** [comment]
Can you please run with `-v 6` and paste the full log?

**Comment by thockin** [comment]
Hi, any update on this?

**Comment by thockin** [comment]
Can you please run with `-v 6` and paste the full log?
