### ISSUE TITLE
Add non atomic behaviour

### ISSUE THREAD

**Issue by stp-ip** [kubernetes/git-sync#53]
Add flag and logic to disable symlink usage and just pull in new changes via git pull.

This could be used as a workaround for various issues and additional use-cases, but introduces inconsistent state so this should be heavily warned about.

Flag: ```GIT_SYNC_ATOMIC```

**Comment by ursuad** [comment]
Maybe an option here would be to introduce a hook  which will get triggered once the pull (update)  is successful? 
For example calling a configurable REST endpoint ( notify ) once the update is complete. This way, it would be really easy to create a wrapper around third party tools  that want to use the git-sync functionality.

The third party tools would get notified once the update is complete. This would partly eliminate the need for non atomic behaviour.

**Comment by thockin** [comment]
That could be workable

**Comment by stp-ip** [comment]
Do we want to add triggering to git-sync?
What trigger should be used? http, touch ready.file, etc.?
Should we still provide a non atomic option?

**Comment by thockin** [comment]
I'd be OK with adding triggers - both HTTP get and file touch seem OK.  I
would not add non-atomic, unless there's significant pain being caused by
symlinks.  I haven't looked closely.

**Comment by stp-ip** [comment]
One of the pain points of symlinks are programs using notify "different" following symlinks and not checking for symlink changes itself. hugo for example.

**Comment by thockin** [comment]
I am fine with non-atomic mode, if people really can't work around it, but
maybe we could fix Hugo ?

**Comment by japettyjohn** [comment]
This would help when the folder becomes the CWD of the app for Go, not sure if this is the same problem in Hugo. In my case the symlink is dereferenced which then leads to explosions when it references a relative file from the non-existent folder.

Another option would be to replace the old folder with a symlink to the new folder. The notification should still be added so things can get reloaded as needed.

**Comment by thockin** [comment]
Do you think #110 would cover this need?

**Comment by stp-ip** [comment]
It doesn't solve it perfectly, but it gives a good workaround I guess. After merge I can take another look and maybe write up some ideas.
