### ISSUE TITLE
Fail to init Airflow scheduler after new commit in git repo

### ISSUE THREAD

**Issue by mriccardi1989** [kubernetes/git-sync#532]
Hello everyone,

We have Airflow in EKS with Helm, two weeks ago we did a commit in the master branch of our Airflow repo and since then the pod running Airflow-scheduler is failing to init due to this error:

`main.go:495]  "level"=0 "msg"="starting up"  "args"=["/git-sync"] "pid"=10
main.go:888]  "level"=0 "msg"="update required"  "local"="7379XXXXXXXXXXX" "remote"="06f8XXXXXXXXXXXf" "rev"="HEAD"
main.go:666]  "level"=0 "msg"="syncing git"  "hash"="06f8XXXXXXXXXXX" "rev"="HEAD"
main.go:168]  "msg"="unexpected error syncing repo, will retry" "error"="Run(git gc --prune=all): exit status 128: { stdout: \"\", stderr: \"fatal: gc is already running on machine 'airflow-scheduler' pid XXX (use --force if not)\\n\" }"`

Is there something that I am doing wrong ?
Thanks in advance!

**Comment by thockin** [comment]
Seems like the same as #439
