### ISSUE TITLE
Add sparse checkout feature

### ISSUE THREAD

**Issue by sdurrheimer** [kubernetes/git-sync#54]
Hi there,

Would be nice if we could sparse checkout a specified list of folders/files.

**Comment by stp-ip** [comment]
Could you give a specific use case, why that would be needed?

**Comment by sdurrheimer** [comment]
This is very usefull when you have multi-purpose repository but you don't want to clone the full repository each each time, it saves time and disk space. 

eg. a repository containing all sort of infrastructure configurations like kubernetes yml files and your json dashboards for grafana but you only want to clone those json as a volume for your grafana deployment.

**Comment by thockin** [comment]
Is there a way to express that to git?

On Mon, Mar 27, 2017 at 12:29 AM, Steve Durrheimer <notifications@github.com

**Comment by sdurrheimer** [comment]
https://git-scm.com/docs/git-read-tree#_sparse_checkout

```
git config core.sparseCheckout true
echo "{REPO_PATH}/{DESIRED_SUBDIR}/*" > .git/info/sparse-checkout
git checkout {BRANCH}
```

**Comment by trnl** [comment]
The problem with sparseCheckout is that still the whole repo will be cloned and then only specified folder will be checked into working tree. So, disk space and time still used.

**Comment by sdurrheimer** [comment]
@trnl `--depth 1` should solve this problem.

**Comment by thockin** [comment]
I don't think --depth solves the same problem OP was asking about.

**Comment by stp-ip** [comment]
So since 2.19 git has a partial clone option, which most likely isn't supported on the server-side widely.
Adding in for context: https://github.com/git/git/blob/v2.19.0/Documentation/technical/partial-clone.txt

In general sparse checkout would still grab the data, but it wouldn't show within the tree.
Reducing the depth is already an optional option.
So sparse checkout seems to really only make sense with partial cloning support in my view.
As the main point is not downloading unnecessary files and not download unnecessary files, but hide them (sparse checkout):

If I missed something, please correct me and add your thoughts.

**Comment by ribbybibby** [comment]
I think that even without the benefits of a partial checkout, sparse checkouts can still be useful in some situations. 

For instance, I have an application that iterates through the folders at the top level of a repository and then does some work with the yaml files it finds in each directory.

See this structure:
```
.
├── team-a_access
│   └── access.yaml
├── team-a_app
│   └── foo.yaml
├── team-b_service
│   └── foo.yaml
│   └── bar.yaml
├── team-c_access
│   └── hola.yaml
│   └── helloworld.yaml
├── team-c_app
│   └── something.yaml
└── team-c_backend
    └── example.yaml
```
 The folders belong to different teams and I would like each team to be able to run a separate deployment of this tool that operates only on their folders. 

If `git-sync` could perform a sparse checkout then I wouldn't need to modify my application to filter the folders or move each teams folders into a separate repo. There are good reasons to try and avoid both of those options for me.

**Comment by cdugga** [comment]
+1 sparse checkout would be a useful feature

**Comment by realei** [comment]
+1 sparse checkout would be a useful feature

**Comment by realei** [comment]
> +1 sparse checkout would be a useful feature

+1 sparse checkout would be a useful feature

this sparse checkout feature is very important for decoupling Static Files from the new features release

**Comment by mirceaaaa** [comment]
> > +1 sparse checkout would be a useful feature
> 
> +1 sparse checkout would be a useful feature
> 
> this sparse checkout feature is very important for decoupling Static Files from the new features release

+1 to this.
A case where this would be exceptionally useful is when using this utility in conjunction with Kubernetes to synchronise Airflow dags that are not isolated in their own separate repo.

**Comment by thockin** [comment]
I'm not inherently against this idea, if someone wants to take a run at a design.  It's not clear if it should be a flag with literal contents or a flag with a filename or something else.

**Comment by jomach** [comment]
I think the main idea is when you specify GIT_SYNC_ROOT that the content of the repo ends there and not inside of a folder
