### ISSUE TITLE
Reminder to flip the default host checking to 'true' on 3.0 version bump

### ISSUE THREAD

**Issue by pieterlange** [kubernetes/git-sync#59]
Ref: #58

**Comment by pieterlange** [comment]
@stp-ip can we cut a new release so people get secure defaults? i think that warrants a version bump anyway.

**Comment by stp-ip** [comment]
@thockin is the person in charge of releases.

**Comment by thockin** [comment]
I have cut a 2.0 release branch, so master can take 3.0 changes.

**Comment by pieterlange** [comment]
Thanks @thockin!
