### ISSUE TITLE
can't remove unusable git root:

### ISSUE THREAD

**Issue by esakarya** [kubernetes/git-sync#598]
{"logger":"","ts":"2022-07-29 14:58:08.689798","caller":{"file":"main.go","line":643},"msg":"can't init root","error":"can't remove unusable git root: openfdat /mnt/git/lost+found: permission denied","/mnt/git":"<no-value>"}

why i can get this error ? i amcan success claim PVC from longhorn and success attach to pod. git-sync getting this error.

**Comment by thockin** [comment]
I see - you have a real filesystem mounted, not just a bind mount.

The simple answer is to point git-sync at a subdir of the mount, to avoid the lost+found dir.

I'll have to think about how best to handle this.  In theory there's any number of "metadata" files that could exist, so hard-coding "lost+found" is not a great idea.  Plus, if your repo happens to have a file called "lost+found", you are in trouble..

**Comment by thockin** [comment]
In fact, git doesn't want you to do this at all.  If I override the failure I get

```
fatal: destination path '/mnt/git' already exists and is not an empty directory.
```

So I guess this is working as intended, but I will update docs a bit.
