### ISSUE TITLE
Cut a new release

### ISSUE THREAD

**Issue by pieterlange** [kubernetes/git-sync#60]
Almost half of the commits in this repo never made it to a released version.

Maybe it's time to cut a new release so we can get more feedback from the users and people don't have to compile their own image.

**Comment by pieterlange** [comment]
@stp-ip @thockin ping

I'm thinking about forking and doing maintenance releases myself so (my) users can get recent builds of this repo without vulnerabilities.

**Comment by stp-ip** [comment]
I don't have access doing releases. For the other issues I scheduled time in July. But some depend on k8s issues.

**Comment by thockin** [comment]
I can cut a release.

**Comment by thockin** [comment]
gcr.io/google-containers/git-sync-amd64:v2.0.5

**Comment by pieterlange** [comment]
Thanks!
