### ISSUE TITLE
git-sync uses `mv -T` which is a non-POSIX GNU extension

### ISSUE THREAD

**Issue by johnsonjh** [kubernetes/git-sync#600]
`mv -T` is not available on the BSD systems (and macOS) so using git-sync requires coreutils - could this dependency be eliminated?

**Comment by johnsonjh** [comment]
I'll check it when I'm in the office, thanks for investigating.

**Comment by johnsonjh** [comment]
Sorry about the delay.

---
1. macOS `/usr/bin/ln -nfs` seems a no-go:
```sh
unlink("x\0", 0x0, 0x0)          = 0 0
symlink("a\0", "x\0")            = 0 0
```
---

2. GNU coreutils ln on macOS works as you want:
```sh
symlinkat("b\0", 0xFFFFFFFFFFFFFFFE, "CuMEC8pe\0")               = 0 0
renameat(0xFFFFFFFFFFFFFFFE, "CuMEC8pe\0", 0xFFFFFFFFFFFFFFFE, "x\0")            = 0 0
```
---

* I see that macOS `mv` **does** offer *`-h`*, which is analogous to GNU's `-T`:
```man
   The following options are available:

   -f      Do not prompt for confirmation before overwriting the destination path.  (The
           -f option overrides any previous -i or -n options.)

   -h      If the target operand is a symbolic link to a directory, do not follow it.
           This causes the mv utility to rename the file source to the destination path
           target rather than moving source into the directory referenced by target.

   -i      Cause mv to write a prompt to standard error before moving a file that would
           overwrite an existing file.  If the response from the standard input begins
           with the character `y' or `Y', the move is attempted.  (The -i option
           overrides any previous -f or -n options.)

   -n      Do not overwrite an existing file.  (The -n option overrides any previous -f
           or -i options.)

   -v      Cause mv to be verbose, showing files after they are moved.
```

**Comment by SMillerDev** [comment]
Why not use something like https://documentation.help/Golang/os.htm#Rename?

**Comment by thockin** [comment]
Unlink+symlink is pathological.  Sigh.  And `ln` on Linux does not have `-h`.  Good job MacOS!

I was exec()ing these commands because it made it easier to manually recreate the exact sync loop that git-sync runs, so I can pick it apart when something goes wrong.  I tried to quickly change it to use `os.Symlink` and it just...doesn't do anything.  I am clearly doing something wrong - there's no error returned but no link created.  I am out of time to debug, and will be taking a code-break for a week or so.  I will look at it when I get a moment.

 ```
$ git diff
diff --git a/cmd/git-sync/main.go b/cmd/git-sync/main.go
index 1418e35..f155d0c 100644
--- a/cmd/git-sync/main.go
+++ b/cmd/git-sync/main.go
@@ -935,8 +935,9 @@ func (git *repoSync) UpdateSymlink(ctx context.Context, newDir string) (string,
                return "", fmt.Errorf("error converting to relative path: %v", err)
        }
 
+       //FIXME: fails tests - does not seem to be making the link?
        git.log.V(1).Info("setting symlink", "root", linkDir, "link", linkFile, "target", newDirRelative)
-       if _, err := git.run.Run(ctx, linkDir, nil, "ln", "-nfs", newDirRelative, linkFile); err != nil {
+       if err := os.Symlink(newDirRelative, linkFile); err != nil {
                return "", fmt.Errorf("error setting symlink: %v", err)
        }
 
```

**Comment by johnsonjh** [comment]
I went the route of [depending on GNU coreutils](https://github.com/Homebrew/homebrew-core/pull/106907) on macOS to keep changes as minimal as possible and so it's using the same commands exactly as on Linux.

It seems like `mv -h` would be fine on macOS and avoid needing GNU coreutils, but I'd want to test it a bit more and check that the `-h` option is available on all supported versions of macOS.  I might have a moment to look at it morethis weekend.

**Comment by thockin** [comment]
I think I have it figured.  Will send a PR againt the v4 branch eventually, not sure if I will backport to v3 yet.

**Comment by johnsonjh** [comment]
Thanks!
