### ISSUE TITLE
Download /  Pull a specific tag with git-sync

### ISSUE THREAD

**Issue by clebercmb** [kubernetes/git-sync#601]
Hi:
I am trying to set up git-sync to pull a specific tag from a git repository, but it is not working. git-sync keeps pulling the latest commit instead of the files from the specific tag.

I am using the following env variables setup for the git-sync:

```
GIT_SYNC_REV=test
GIT_SYNC_REPO=<repository link>
GIT_SYNC_DEPTH=1
GIT_SYNC_ROOT=/git
GIT_SYNC_DEST=dags
GIT_SYNC_GIT_CONFIG=http.sslVerify:false
GIT_SYNC_WAIT=600
```

Can someone help me to figure out what is wrong with my setup? Does someone have a sample about how I should set up git-sync to pull a specific tag from a git repository?

Thank you

**Comment by thockin** [comment]
IIRC, using depth and a tag name might not work, if the branch being cloned
doesn't have the tag within 'depth' commits.

I have a plan to make this better, but for now you probably need to change
'depth'.

That said, I am taking a few days away from my computer, so I will look at
this more when I get back to it.

**Comment by thockin** [comment]
So I did some testing and a) unveiled an inefficiency in git-sync, which will need deeper changes to fix properly (not wrong, just inefficient); b) shows a bug where initial behavior (clone) differs from later behavior (fetch); c) rationalized why this case is supposed to work, but doesn't always.

When we `git clone` we pull the `--branch`.  If the `--rev` is not available within `--depth` commits, it is an error.

```
$ rm -rf /tmp/g-s-test; bin/linux_amd64/git-sync --root=/tmp/g-s-test --repo=http://github.com/kubernetes/git-sync --branch master --rev v3.2.0 --depth 1 --one-time
{"logger":"","ts":"2022-08-15 10:27:43.114895","caller":{"file":"main.go","line":429},"level":0,"msg":"starting up","pid":148724,"uid":8119,"gid":89939,"home":"/home/thockin","args":["bin/linux_amd64/git-sync","--root=/tmp/g-s-test","--repo=http://github.com/kubernetes/git-sync","--branch","master","--rev","v3.2.0","--depth","1","--one-time"],"env":["SHELL=/bin/bash","HOME=/home/thockin","USERNAME=thockin"]}
{"logger":"","ts":"2022-08-15 10:27:43.129115","caller":{"file":"main.go","line":829},"level":0,"msg":"sanity-checking git repo","repo":"/tmp/g-s-test"}
{"logger":"","ts":"2022-08-15 10:27:43.129267","caller":{"file":"main.go","line":836},"level":0,"msg":"git repo is empty","repo":"/tmp/g-s-test"}
{"logger":"","ts":"2022-08-15 10:27:43.129289","caller":{"file":"main.go","line":810},"level":0,"msg":"root directory is valid","path":"/tmp/g-s-test"}
{"logger":"","ts":"2022-08-15 10:27:43.129322","caller":{"file":"main.go","line":1216},"level":0,"msg":"cloning repo","origin":"http://github.com/kubernetes/git-sync","path":"/tmp/g-s-test"}
{"logger":"","ts":"2022-08-15 10:27:44.238074","caller":{"file":"main.go","line":655},"msg":"too many failures, aborting","error":"Run(git rev-parse v3.2.0): exit status 128: { stdout: \"v3.2.0\", stderr: \"fatal: ambiguous argument 'v3.2.0': unknown revision or path not in the working tree.\\nUse '--' to separate paths from revisions, like this:\\n'git <command> [<revision>...] -- [<file>...]'\" }","failCount":1}
```

When we `git fetch` we pull both the branch and the tags, so we DO have the tag with depth=1.   Maybe we can fix that with an initial fetch.  It makes things even less efficient, but it should work.  Or maybe we can fetch the tag alone if it doesn't resolve.  Will need to think about it...
