### ISSUE TITLE
Using HTTPS with an embedded username and PAT causes it to print in logs

### ISSUE THREAD

**Issue by katefort** [kubernetes/git-sync#602]
Using a repository URL without a PAT and username does not work.
`E0809 16:38:35.073853      12 main.go:539] "msg"="error syncing repo, will retry" "error"="Run(git clone -v --no-checkout -b main --depth 1 https://github.com/MyRepo/manifests.git /var/git-sync): exit status 128: { stdout: "", stderr: "Cloning into '/var/git-sync'...\nremote: Support for password authentication was removed on August 13, 2021.\nremote: Please see https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication.\nfatal: Authentication failed for 'https://github.com/MyRepo/manifests.git/'" }" "failCount"=1 "waitTime"=60000000000`

Alternatively, using a repository URL with a PAT and username does work, but it causes the PAT to be printed in the kubectl logs (as part of the url). This seems like a security issue... Is there a way to fix this?

Which one is intended? Am I missing something?

Thanks in advance.

**Comment by thockin** [comment]
How are you currently passing the username and password such that it fails?  Are you passing a password or a PAT?

What is the struture URL you are using for the PAT (it seems reasonable to redact that :).

As I understand it, a PAT is an alternative to password - you should be able to use the PAT in --password or --askpass-url or --password-file (or their associated env vars).

**Comment by katefort** [comment]
Hi Tim! I was passing a password file via the GIT_SYNC_PASSWORD. It's possible I was using the wrong one, and I'm testing that now. I got it to work using the --password-file arg. Is using a file path as git_sync_password still supported?

**Comment by thockin** [comment]
no, GIT_SYNC_PASSWORD must be a password, GIT_SYNC_PASSWORD_FILE is a filename.  They all plumb into the same mechanism, so a PAT in any of them should work.

I have put up a PR to redact passwds in URLs, too.  Thanks.
