### ISSUE TITLE
Unable to work within a branch after a sync

### ISSUE THREAD

**Issue by luksi1** [kubernetes/git-sync#603]
We work with a lot of Jupyter Notebooks and noticed when using git-sync with a third party product that we are unable to work within that branch when using this as an init-container. So we're starting with the original project to see if this is a feature, bug, or if we are mis-using git-sync.

If we use git-sync, the .git directory is created in the root directory, not the directory for the clone.

For instance, if we using the following command:

```bash
docker run -u $(id -u):$(id -g) -v /tmp/code:/tmp/code \
-e GIT_SYNC_REPO=https://git.domain.com/git-repository \
-e GIT_SYNC_BRANCH=main \
-e GIT_SYNC_ROOT=/tmp/code \
-e GIT_SYNC_ONE_TIME="true" \
-e GIT_SYNC_REV="HEAD" \
-e HOME=/tmp \
registry/git-sync:1.0__linux_amd64
```

This will produce a git structure as the following:

```bash
luksi1@server:/tmp/code$ ls -latr .git
total 64
drwxr-xr-x 2 luksi1 luksi1 4096 Aug 11 17:51 info
drwxr-xr-x 2 luksi1 luksi1 4096 Aug 11 17:51 hooks
-rw-r--r-- 1 luksi1 luksi1   73 Aug 11 17:51 description
drwxr-xr-x 2 luksi1 luksi1 4096 Aug 11 17:51 branches
drwxr-xr-x 5 luksi1 luksi1 4096 Aug 11 17:51 refs
-rw-r--r-- 1 luksi1 luksi1  252 Aug 11 17:51 packed-refs
drwxr-xr-x 3 luksi1 luksi1 4096 Aug 11 17:51 logs
-rw-r--r-- 1 luksi1 luksi1   21 Aug 11 17:51 HEAD
-rw-r--r-- 1 luksi1 luksi1  281 Aug 11 17:51 config
-rw-r--r-- 1 luksi1 luksi1  120 Aug 11 17:51 FETCH_HEAD
drwxr-xr-x 4 luksi1 luksi1 4096 Aug 11 17:51 objects
drwxr-xr-x 3 luksi1 luksi1 4096 Aug 11 17:51 worktrees
-rw-r--r-- 1 luksi1 luksi1   41 Aug 11 17:51 ORIG_HEAD
-rw-r--r-- 1 luksi1 luksi1 1506 Aug 11 17:51 index
drwxr-xr-x 9 luksi1 luksi1 4096 Aug 11 17:51 .
drwxrwxr-x 6 luksi1 luksi1 4096 Aug 11 17:51 ..
luksi1@server:/tmp/code$ ls -latr git-repository/.git
-rw-r--r-- 1 luksi1 luksi1 67 Aug 11 17:51 git-repository/.git
```

Notice that the .git directory under "git-repository" is empty, while the correct .git directory is located one directory up. This means users are unable to change, commit, and push their code as they would expect.

What I would have expected is that the .git directory one directory up would be located in the "git-repository" directory, just the same as it would appear when performing a `git clone`.

Please let us know if there is any other information you need.

**Comment by thockin** [comment]
I think git-sync is not exactly what you want.  git-sync is designed to PULL code so other containers can READ it.  It sets things up in a way that is tailored to that, at the cost of not being "normal" for people who want to use it like a working repo with new commits and such.

In this case your `/tmp/code` is the git repo, but it was created with --no-checkout.  `/tmp/code/git-repository` is a symlink to a git worktree at the specific hash that was checked out.  This allows us to "track" revs with atomic behavior - readers see either the old hash or the new, but never a mix.

For example if you are tracking the "main" branch, we would:
  1) clone the repo+branch to /tmp/code with --no-checkout
  2) observe HEAD is hash abc123
  3) create a worktree for abc123
  4) create symlink: git-repository -> abc123
  5) readers who look at /tmp/code/git-repository will always see hash abc123
  6) someone makes a new commit an d pushes it upstream
  7) git-sync observes that the remote hash for HEAD is now def456
  8) fetch the changes
  9) create another worktree for def456 (readers are still seeing abc123)
  10) create a temp symlink -> def456
  11) rename temp link to git-repository (atomic)
  12) readers who look at /tmp/code/git-repository will now see hash def456

What you see in `git-repository/.git` is a file, which is what git does with worktrees.  You should still be able to make commits, but they are "detached head" - if you want to push it upstream you need to manage that yourself.

If you just want to check out the repo and use it, you have to deal with conflicts and things like that, which git-sync does not handle.  You might be better off just using a simple base image with `git` in it and running `git clone` yourself?

**Comment by luksi1** [comment]
Thanks for the answer and for making it much more clear. We'll contact our third-party supplier and discuss what would be a good fit for these scenarios. Maybe, like you said, simply using git clone ourselves might the easiest way forward.
