### ISSUE TITLE
Host key verification ENV looks at GIT_KNOWN_HOSTS not GIT_SYNC_KNOWN_HOSTS

### ISSUE THREAD

**Issue by Milkshak3s** [kubernetes/git-sync#634]
When attempting to set `GIT_SYNC_KNOWN_HOSTS` to `false` to no avail, discovered that in fact only setting `GIT_KNOWN_HOSTS` to `false` allows host key verification to be disabled.

**Comment by thockin** [comment]
What version of git-sync?

in HEAD it should accept either one, but prefer GIT_SYNC_KNOWN_HOSTS.  This is only on the v4 dev branch, which has not has a release yet.

Older versions should only support GIT_KNOWN_HOSTS
