### ISSUE TITLE
Permission denied if changing the root directory

### ISSUE THREAD

**Issue by MISSEY** [kubernetes/git-sync#635]
When I change the `GIT_SYNC_ROOT` to custom directory such as `git1`, getting permission denied error. 

**Version 3.6.1**
```bash
INFO: detected pid 1, running init handler
I0927 14:23:21.826754      11 main.go:389] "level"=0 "msg"="starting up" "pid"=11 "args"=["/git-sync"]
I0927 14:23:21.895433      11 main.go:934] "level"=0 "msg"="cloning repo" "origin"="https://git.ni.dfki.de/ml_infrastructure/airflow-dags-2.git" "path"="/git1"
E0927 14:23:21.900957      11 main.go:535] "msg"="too many failures, aborting" "error"="Run(git clone -v --no-checkout -b main --depth 1 https://git.ni.dfki.de/ml_infrastructure/airflow-dags-2.git /git1): exit status 128: { stdout: "", stderr: "fatal: could not create work tree dir '/git1': Permission denied" }" "failCount"=1
```

**Comment by MISSEY** [comment]
Now, If, I changed the `GIT_SYNC_ROOT` to `tmp/git`, still getting permission error.

**HEML VALUES**

```yaml

name: git-sync-2
      image: 'k8s.gcr.io/git-sync/git-sync:v3.6.0'
      env:
        - name: GIT_SYNC_USERNAME
          valueFrom:
            secretKeyRef:
              name: git-credentials-2
              key: GIT_SYNC_USERNAME
        - name: GIT_SYNC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: git-credentials-2
              key: GIT_SYNC_PASSWORD
        - name: GIT_SYNC_REV
          value: HEAD
        - name: GIT_SYNC_BRANCH
          value: main
        - name: GIT_SYNC_REPO
          value: 'https://git.ni.dfki.de/ml_infrastructure/airflow-dags-2.git' 
        - name: GIT_SYNC_DEPTH
          value: '1'
        - name: GIT_SYNC_ROOT
          value: /tmp/git
        - name: GIT_SYNC_DEST
          value: /git
        - name: GIT_SYNC_ADD_USER
          value: 'true'
        - name: GIT_SYNC_WAIT
          value: '60'
        - name: GIT_SYNC_MAX_SYNC_FAILURES
          value: '0'
        - name: GIT_SYNC_PERMISSIONS
          value: '0777'
      resources: {}
      volumeMounts:
        - name: dags2
          mountPath: /git
          # readOnly: true
        # - name: kube-api-access-9j29g
        #   readOnly: true
        #   mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      imagePullPolicy: IfNotPresent
      securityContext:
        runAsUser: 65533
```

```bash

INFO: detected pid 1, running init handler
I0928 10:23:52.277416      11 main.go:389] "level"=0 "msg"="starting up" "pid"=11 "args"=["/git-sync"]
I0928 10:23:52.296331      11 main.go:934] "level"=0 "msg"="cloning repo" "origin"="https://git.ni.dfki.de/ml_infrastructure/airflow-dags-2.git" "path"="/tmp/git"
I0928 10:23:52.511177      11 main.go:748] "level"=0 "msg"="syncing git" "rev"="HEAD" "hash"="1a869978271ddde92e9dd487ee7a64c22d0f430e"
I0928 10:23:52.707362      11 main.go:783] "level"=0 "msg"="adding worktree" "path"="/tmp/git/1a869978271ddde92e9dd487ee7a64c22d0f430e" "branch"="origin/main"
I0928 10:23:52.711165      11 main.go:844] "level"=0 "msg"="reset worktree to hash" "path"="/tmp/git/1a869978271ddde92e9dd487ee7a64c22d0f430e" "hash"="1a869978271ddde92e9dd487ee7a64c22d0f430e"
I0928 10:23:52.711215      11 main.go:849] "level"=0 "msg"="updating submodules"
I0928 10:23:52.744049      11 main.go:866] "level"=0 "msg"="changing file permissions" "mode"="0777"
E0928 10:23:52.746588      11 main.go:535] "msg"="too many failures, aborting" "error"="error creating symlink: Run(ln -snf tmp/git/1a869978271ddde92e9dd487ee7a64c22d0f430e tmp-link): exit status 1: { stdout: "", stderr: "ln: failed to create symbolic link 'tmp-link': Permission denied" }" "failCount"=1


```

**Comment by thockin** [comment]
> "error creating symlink: Run(ln -snf tmp/git/1a869978271ddde92e9dd487ee7a64c22d0f430e tmp-link): exit status 1: { stdout: "", stderr: "ln: failed to create symbolic link 'tmp-link': Permission denied"

This says "tmp/git" and not "/tmp/git" - is that a cut-paste problem?

Also:

>         - name: GIT_SYNC_DEST
>           value: /git

This should not have a leading slash - that should not even be allowed.  We validate that it has no `/` characters.

Also:  Your volume is still mounted at `/git`.

Regardless it's still giving you a permission problem.  It looks like it was able to make a worktree at `/tmp/git`, but somehow you have tricked it into making the symlink in `tmp/git` (no leading slash).  I can't quite see how, though.  When I use those args I get a validation error (as expected).

```
$ bin/linux_amd64/git-sync -root /tmp/git -dest /git -repo https://github.com/kubernetes/git-sync
ERROR: --dest must be a leaf name, not a path
```

if I fix that I get no error (as expected):

```
$ bin/linux_amd64/git-sync -root /tmp/git -dest git -repo https://github.com/kubernetes/git-sync
I0928 08:59:08.174961 1185423 main.go:440]  "level"=0 "msg"="starting up"  "args"=["bin/linux_amd64/git-sync","-root","/tmp/git","-dest","git","-repo","https://github.com/kubernetes/git-sync"] "pid"=1185423
I0928 08:59:08.175078 1185423 main.go:704]  "level"=0 "msg"="cloning repo"  "origin"="https://github.com/kubernetes/git-sync" "path"="/tmp/git"
I0928 08:59:14.521438 1185423 main.go:596]  "level"=0 "msg"="syncing git"  "hash"="34c33c724ac3625348f95ed2f76e0fbf43f35510" "rev"="HEAD"
I0928 08:59:15.166975 1185423 main.go:617]  "level"=0 "msg"="adding worktree"  "branch"="origin/master" "path"="/tmp/git/rev-34c33c724ac3625348f95ed2f76e0fbf43f35510"
I0928 08:59:15.251710 1185423 main.go:640]  "level"=0 "msg"="reset worktree to hash"  "hash"="34c33c724ac3625348f95ed2f76e0fbf43f35510" "path"="/tmp/git/rev-34c33c724ac3625348f95ed2f76e0fbf43f35510"
I0928 08:59:15.251730 1185423 main.go:645]  "level"=0 "msg"="updating submodules"  
```

You could try running this as a pod but change the `command` to "sh" and args to [ "-c", "sleep inf"] then you can `kubectl exec` into it and poke around the filesystem to see permissions.

**Comment by MISSEY** [comment]
First of all, thank you so much. I want to keep `GIT_SYNC_ROOT` and `GIT_SYNC_DEST` different. Is it possible to keep them separate? I only want to access files in the repo not the work tree of the repo. 

```bash
total 16
drwxrwsrwx 4 root     root 4096 Sep 28 16:22 .
drwxr-xr-x 1 root     root 4096 Sep 28 16:22 ..
drwxr-sr-x 9 git-sync root 4096 Sep 28 16:22 .git
drwxr-sr-x 3 git-sync root 4096 Sep 28 16:22 1a869978271ddde92e9dd487ee7a64c22d0f430e
lrwxrwxrwx 1 git-sync root   40 Sep 28 16:22 repo -> 1a869978271ddde92e9dd487ee7a64c22d0f430e

```

Is it possible somehow to keep repo and `1a869978271ddde92e9dd487ee7a64c22d0f430e` separate directories ?

**Comment by thockin** [comment]
I'm not sure exactly what you mean.  The worktree IS the repo.  That's how
we provide "atomic" views.  We don't even checkout the raw repo because it
would be potentially inconsistent while a new pull is happening.  For
example:

* repo has 2 files "x" and "y"
* you sync to hash abc123
* your app accesses the two files
* upstream changes to hash def456
* we start syncing and checking out the new hash
* your app reads "x" at abc123 and "y" at def456 - inconsistent

The way we use worktrees prevents that.

I don't understand what you are really asking for?

**Comment by MISSEY** [comment]
Hey, I am sorry I couldn't explain you. 
I am using git-syn for dags in airflow. When I mount repository in dags directory in airflow, for eg. /git into <respective dags dir>, there is redundancy of files, as /git consists of work-tree (1a869978271ddde92e9dd487ee7a64c22d0f430e) and repo, both have same files. This is creating problems in airflow. I want only want /git/repo to be mounted in  <respective dags dir> in airflow.  This is why I want to separate work-tree and repo. Currently they both are in /git .

**Comment by thockin** [comment]
I get it, but that is not how git-sync works.

There is no "/git/repo" there is only "/git/$dest -> $hash".  If we
don't do it that way, I do not know how to provide atomic updates when
the hash changes.  If you don't care about the hash changing (you only
want to sync once), perhaps you should use an initContainer and
`git-sync --one-time` ?

I have had one or two requests for non-atomic mode but it's
complicated and really not much demand.

Can't you point airflow DAG_FOLDER at `/git/dest` (which is a symlink)
rather than /git?

**Comment by thockin** [comment]
Does the user you are running as (default is NOT root) have permissions to
write to /?  I bet not.
