### ISSUE TITLE
How to deal with slow syncing via `git fetch`

### ISSUE THREAD

**Issue by dmattia** [kubernetes/git-sync#637]
Hello, I have a question on the performance I'm seeing when on a larger repo:

<img width="1172" alt="Screen Shot 2022-10-14 at 12 29 14 PM" src="https://user-images.githubusercontent.com/8922077/195929074-c7db8a19-aa14-4948-8e2f-f9660a2d0d1d.png">

In the picture above, it shows that cloning my repo takes about 15 seconds (time between `cloning repo` and `syncing git`).
Then `syncing git` takes 1 minute 17 seconds, though I've seen this timeout as over two minutes on some runs.  The code between the `syncing git` and `adding worktree` sections is here: https://github.com/kubernetes/git-sync/blob/34c33c724ac3625348f95ed2f76e0fbf43f35510/cmd/git-sync/main.go#L1062-L1098, and it appears to run `git fetch -f --tags --depth 1 <repo> <branch_name>` in my case, as `GIT_SYNC_DEPTH` is set to `1`.

Is there anything that could be done to speed up this process? It almost seems like it would be faster to re-clone the repo checkout the specific branch, which seems wrong, so maybe I'm configuring something incorrectly?

Please let me know if there's any more information I could provide. I am on the latest released version

**Comment by thockin** [comment]
Hi, I am trying to repo this but failing.  Even if I force a really large repo (the clone takes almost 20 seconds) I do not see any notable slowdown on `fetch` or `worktree add`.

Can you show me all the flags and environment vars you use?  If there's a repo that you are using to demonstrate this, or if you can make a public repo that shows the behavior, I can dig in.

We could elide the worktree stuff but ONLY in the case of `--one-time` and even then I would rather not have a totally different code path, if it can be avoided.  So step 1 is to reproduce it.
