### ISSUE TITLE
[Discussion] Is there any way to track submodules directly?

### ISSUE THREAD

**Issue by nirutgupta** [kubernetes/git-sync#645]
Lets say I have repo A and inside that repo there is a submodule B
If any change happens to A k8s git sync catches it and syncs the repo
`I1122 02:22:59.203144      12 main.go:888]  "level"=0 "msg"="update required" `
But I want the same behaviour even when submodule gets changed. 

Is there any way to achieve that? Thank you.

**Comment by thockin** [comment]
There is a submodule tracking PR which I am have let languish (bad
maintainer, me).  I think that is what you want.  I'll have to dust that
off..

**Comment by nirutgupta** [comment]
Sure, can you share the PR here ?

**Comment by thockin** [comment]
It's open against this repo (on mobile, sorry)

**Comment by thockin** [comment]
Dup of #265
