### ISSUE TITLE
Git Sync is not working in Mac M1 Chip

### ISSUE THREAD

**Issue by tanvircefalo** [kubernetes/git-sync#650]
I am using git sync in airflow as a sidecar container. It is working fine for Linux and Windows with an amd64 chip. But when I am trying to deploy it in the Mac M1 ARM64 machine it is not working. 

INFO: detected pid 1, running init handler
I1125 16:39:16.921249      15 main.go:389] "level"=0 "msg"="starting up" "pid"=15 "args"=["/git-sync"]
I1125 16:39:16.926850      15 main.go:934] "level"=0 "msg"="cloning repo" "origin"="git@github.com:Kontali/ETL.git" "path"="/git"
E1125 16:39:18.799562      15 main.go:535] "msg"="too many failures, aborting" "error"="Run(git clone -v --no-checkout -b master --depth 1 git@github.com:Kontali/ETL.git /git): exit status 128: { stdout: "", stderr: "Cloning into '/git'...\nWarning: Permanently added 'github.com,20.205.243.166' (ECDSA) to the list of known hosts.\r\nLoad key \"/etc/git-secret/ssh\": invalid format\r\ngit@github.com: Permission denied (publickey).\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists." }" "failCount"=1

I am getting this error. But with the same configuration, it is working fine for Linux and Windows.

Do I need to use a different image for mac?

**Comment by thockin** [comment]
It is getting permission denied reading the secret - check that.

**Comment by tanvircefalo** [comment]
Hi, I am using terraform and airflow helm chart to deploy airflow in the Kubernetes cluster(Kind Cluster). With the same configuration and id_rsa the git sync sidecar is working properly on ubuntu and windows machines. But when I am trying to deploy in m1 machine, it is showing that error. I do not know why this happened. Any thoughts?

**Comment by thockin** [comment]
Can you reduce the number of variables? Like, can you just 'docker run' it
and see what happens?
