### ISSUE TITLE
Allow sync wait time to be truncated so that a sync occurs immediately.

### ISSUE THREAD

**Issue by trulede** [kubernetes/git-sync#660]
We would like to trigger a sync immediately, either from our CI systems pushing a change out, or interactively while debugging. Currently when we use git-sync as a sidecar container we can do this by deleting the Pod, after which the deployment recreates the Pod (and the sync occurs) - but it is a bit messy.

The most recent use case I've had for this has been to push Hugo based documentation to an NGINX container. In this case, git-sync is used to pull the Hugo publish branch from the doc repo to a volume on a Pod, from which the NGINX container serves static content. The wait duration we use is 3600s, but could easily be set higher since normally the content of the published branch does not change too often.

I've made a simple prototype which truncates the wait time using a signal (os.Interrupt). If you like I could open a PR with that change and develop it further.

Related issues: #226 #482

**Comment by thockin** [comment]
I'm not opposed to either signal or HTTP, it just needs some design work.  Those obviously solve for different things - signals require a local agent, HTTP can be over network but requres some amount of trust.

**Comment by trulede** [comment]
Right. Using a signal will require a sidecar no matter what (technique described here: [Share Process Namespace](https://kubernetes.io/docs/tasks/configure-pod-container/share-process-namespace/#configure-a-pod)). Otherwise it's fairly straight forward.

With HTTP I guess it's a bit tricky. Use the existing endpoint (and trust ... ) or create a new one specifically for the purpose (of control)? I'm not really sure what to do there, but interested- Perhaps in my use case (CI system) I don't want to deal with that, so a signal is easier to deal with, however I suspect my use case is rather narrow in scope.

In any case, to support the discussion, I opened a PR (#664 ) with my signal based implementation.

**Comment by trulede** [comment]
Solution using signals is available via #664
