### ISSUE TITLE
issue when trying to use git sync

### ISSUE THREAD

**Issue by alon050** [kubernetes/git-sync#693]
git-sync:v3.5.0
i have 2 containers running on a pod. 1 is git-sync, the second is airflow.
first container named: sync-repositories, the second named: airflow-scheduler.
there's also a container volume: git-cloned-dags.
sync-repositories's mount path on the volume is: /dags
the airflow-scheduler is mounted on the path: /opt/bitnami/airflow/dags/git_dags
the sync-repositories configuration is as follows:
GIT_SYNC_REPO: https://path/to/repo
GIT_SYNC_BRANCH: master
GIT_SYNC_REV: HEAD
GIT_SYNC_ROOT: /dags
GIT_SYNC_DEST:dags
GIT_SYNC_WAIT: 15
GIT_SYNC_MAX_SYNC_FAILURES:0
GIT_SYNC_DEPTH: 1
GIT_SYNC_TIMEOUT: 120

that way, the sync-repositories container always fails at first try with the following error: error replacing symlink: Run(mv -T tmp-link-dags): exit status1: {stdout:"", stderr: "mv: cannot overwrite directory 'dags' with non-directory\n"} "failcount"=0

than in the second restart, it does clone the repo to the required location on the container, as a sym-link.
that means that so far in the sync-repositories, there is the latest commit in the /dags folder, and a folder /dags/dags and here are the files with the sym-link to the latest commit.
on the airflow-scheduler container there is nothing in the folder that is mounted to that volume. and if i try and create a file there it says, that there is no such directory: /opt/bitnami/airflow/dags/git_dags.
so the volume does contain all of the git-sync files needed but in the second container, when i add the subpath mentioned earlier, the folder is empty.
i tried adding an init-container that does sync once, and it works, but, after changes in the git repo, the sync container updates the files and they won't appear on the main container again.
I have tried to tinker with setting and with the volume but no luck, i would love to have some help.

**Comment by thockin** [comment]
You can't use subpath on symlink - the kernel dereferences it once, so it
will never update.  Worse, the volume mount logic will mkdir the mountpoint
if it doesn't exist, so what you end up with is an empty directory.

You have to volume-mount the whole /dags directory.

**Comment by alon050** [comment]
but i dont want the mian container to see the original directory. only the symlink. isnt that possible somehow?

**Comment by thockin** [comment]
You have to volume mount the whole directory - subpath does not do what you
want with symlinks.  I wish it were better but it is just how Linux works.

You can put another symlink somewhere else that points back to the git-sync
link, if you want to hide it, but that's not something git-sync can do for
you.

E. G. Mount the shared volume at /git (so the link is /git/dags, targeting
the hash worktree).  Then `ln -s /git/dags /dags` and point your app at
/dags.

**Comment by thockin** [comment]
Another thought that might be worth calling ouot:

git-sync always "publishes" a synced repo via a symlink.  You can put that symlink anywhere that git-sync is able to write - for example, you can use "/tmp/git-sync" as the `--root`, and "/git/dags" as the `--dest`.  /git/dags will be symlink to `/tmp/git-syc/<something you should not hardcode>` which is the "current" state of the git repo.
