### ISSUE TITLE
update to 3.6.4 breaks git sync

### ISSUE THREAD

**Issue by vsubram95** [kubernetes/git-sync#696]
git-sync v3.6.4 breaks the cloning process in our k8s pods with the issue mentioned. However, it works fine until version v3.6.3 . 

Note: 
1. We use **submodules** in our repos.
2. This is **git-sync** deployed as sidecar container in airflow via helm

````
12 main.go:535] "msg"="too many failures, aborting" "error"="Run(git rev-parse HEAD): exit status 128: { stdout: "", stderr: "fatal: detected dubious ownership in repository at '/dags'
To add an exception for this directory, call:

\tgit config --global --add safe.directory /dags" }" "failCount"=1
````

**Comment by thockin** [comment]
This looks like a fairly recent change in git. I will have to figure out
what tickles this and add a test case.

**Comment by thockin** [comment]
Ok, well the fix is pretty easy.  I will try to prep a PR this week.

**Comment by thockin** [comment]
https://github.com/kubernetes/git-sync/releases/tag/v3.6.5

**Comment by thockin** [comment]
Can you show me:

1) Full logs with `-v 6`
2) Your full commandline and env vars (you can XXX the repo and stuff)

**Comment by vineetnegi009** [comment]
here are the logs for the git-sync sidecar container:

I0321 06:40:40.730611      13 main.go:539] "level"=1 "msg"="syncing repo"
I0321 06:40:40.730673      13 main.go:950] "level"=0 "msg"="cloning repo" "origin"="<git-repo>" "path"="/tmp"
I0321 06:40:40.730687      13 main.go:952] "level"=5 "msg"="running command" "cwd"="" "cmd"="git clone -v --no-checkout -b master --depth 1 <git-repo> /tmp"
I0321 06:40:40.732234      13 main.go:956] "level"=0 "msg"="git root exists and is not empty (previous crash?), cleaning up" "path"="/tmp"
I0321 06:40:40.732307      13 main.go:623] "level"=2 "msg"="removing path recursively" "path"="/tmp/.git" "isDir"=true
I0321 06:40:40.733731      13 main.go:964] "level"=5 "msg"="running command" "cwd"="" "cmd"="git clone -v --no-checkout -b master --depth 1 <git-repo> /tmp"
I0321 06:40:42.125068      13 main.go:964] "level"=6 "msg"="command result" "stdout"="" "stderr"="Cloning into '/tmp'...
Failed to add the RSA host key for IP address 'x.x.x.x' to the list of known hosts (/etc/git-secret/known_hosts)."
I0321 06:40:42.125088      13 main.go:974] "level"=0 "msg"="configuring sparse checkout"
I0321 06:40:42.125200      13 main.go:1006] "level"=5 "msg"="running command" "cwd"="/tmp" "cmd"="git sparse-checkout init"
E0321 06:40:42.126918      13 main.go:551] "msg"="error syncing repo, will retry" "error"="Run(git sparse-checkout init): exit status 128: { stdout: "", stderr: "fatal: detected dubious ownership in repository at '/tmp'\nTo add an exception for this directory, call:\n\n\tgit config --global --add safe.directory /tmp" }" "failCount"=3 "waitTime"=60000000000


and the args for the sync container are:
  - args:
    - -repo=<git-repo>
    - -branch=master
    - -depth=1
    - -max-sync-failures=-1
    - -git-config=core.filemode:false
    - -wait=60
    - -ssh=true
    - -v=6
    - -root=/tmp
    - -dest=dashboards
    - -sparse-checkout-file=/sparse-file
      securityContext:
      runAsUser: 65533

**Comment by vineetnegi009** [comment]
yes, changing the --root to /tmp/git  resolved the problem with git-sync.
