### ISSUE TITLE
Document or error on GIT_SYNC_DEST not being a subdirect of GIT_SYNC_ROOT

### ISSUE THREAD

**Issue by stp-ip** [kubernetes/git-sync#7]
I just ran into the issue, that the symlink created for GIT_SYNC_DEST is not an absolute link therefore it needs to be a subdir of GIT_SYNC_ROOT to function. Furthermore the GIT_SYNC_ROOT directory also has to be mounted as volume or else the symlink might fail due to filesystem boundaries.

**Comment by thockin** [comment]
can you clarify what you did and what happened, so I can document it?

**Comment by stp-ip** [comment]
Basically I set GIT_SYNC_DEST to /etc/source, but did not set GIT_SYNC_ROOT directory.
Both need to be set as far as I understood code and errors. Additionally GIT_SYNC_DEST needs to be a subdirectory under the GIT_SYNC_ROOT directory.

**Comment by thockin** [comment]
Comments are updated and an error is generated now (v2.0.1)
