### ISSUE TITLE
Accessing private repos with SSH

### ISSUE THREAD

**Issue by StrandedKitty** [kubernetes/git-sync#702]
I can't figure out how to use git-sync with SSH. I'm using openweb/git-sync:0.0.1. My command for running a container is:

```
docker run --rm --name git-sync \
    -e GIT_SYNC_REPO=https://github.com/StrandedKitty/streets-gl-tile-server.git \
    -e GIT_SYNC_DEST=/git \
    -e GIT_SYNC_BRANCH=main \
    -e GIT_SYNC_REV=FETCH_HEAD \
    -e GIT_SYNC_WAIT=10 \
    -e GIT_SYNC_SSH=true \
    -e GIT_SSH_KEY_FILE=/git-secret/id_ed25519 \
    -e GIT_KNOWN_HOSTS=false \
    -v ./test:/git \
    -v ./git-secret:/git-secret \
    openweb/git-sync:0.0.1
```

My SSH private key is located in ./git-secret/id_ed25519:
```
~/nginx# cat git-secret/id_ed25519
-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXkt.....
```

With public repositories it works just fine, but when trying to clone a private repository there is a problem with username:
```
2023/03/23 17:16:30 error syncing repo: error cloning repo "git clone --no-checkout -b main https://github.com/StrandedKitty/streets-gl-tile-server.git /git": exit status 128: Cloning into '/git'...
fatal: could not read Username for 'https://github.com': No such device or address
```

I've tried adding GIT_SYNC_USERNAME with my email and github username, but I get the same error.

I've also tried using ssh repo url (`ssh://git@github.com:StrandedKitty/streets-gl-tile-server.git`), but like this I always get `Host key verification failed. fatal: Could not read from remote repository.` even with public repos.

**Comment by thockin** [comment]
> GIT_SYNC_REPO=https://github.com/StrandedKitty/streets-gl-tile-server.git 

You are telling git that it's an HTTPS server, then asking for git over ssh, but not specifying the username.  Unfortunately, the `--username` flag isn't for SSH.  You want `git@github.com:user/repo` or `ssh://git@github.com/user/repo` (note where the colon goes in each) syntax.  For example:

Bad syntax:
```
$ git clone ssh://git@github.com:thockin/git-sync
Cloning into 'git-sync'...
ssh: Could not resolve hostname github.com:thockin: Name or service not known
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Good ssh:// syntax:
```
$ git clone ssh://git@github.com/thockin/git-sync 
Cloning into 'git-sync'...
```

Good SCP-ish syntax:
```
$ git clone git@github.com:thockin/git-sync
Cloning into 'git-sync'...
```
