### ISSUE TITLE
Add support for json/structured logging

### ISSUE THREAD

**Issue by feniix** [kubernetes/git-sync#707]
Hi, it'd be nice to have support to chose the logging format.

text (which is current) and json

**Comment by thockin** [comment]
In the v4 branch I have switched to JSON.  I could MAYBE see an argument for allowing that to be configured

**Comment by thockin** [comment]
Ehh, I looked at this - since I use logr, the textoutput isn't the traditional sort of output, and I don't think choosing between structured and non-structured logs is somethign I want to do.

So I think the answer is - v4 will solve this!

**Comment by mcarbonneaux** [comment]
using another log library ?!
like https://github.com/rs/zerolog  or https://github.com/sirupsen/logrus or https://github.com/uber-go/zap ?
