### ISSUE TITLE
Difficult to use multiple git-sync instances on the same shared volume mount

### ISSUE THREAD

**Issue by ketozhang** [kubernetes/git-sync#709]
On the same volume mount, multiple git-sync instance would share the same `--root` such that I want to accomplish something like this:

```
/tmp/git
  repo1
  repo2
```

```
$ docker run -v shared:/tmp/git git-sync --repo=<REPO1> --root=/tmp/git --dest=repo1
$ docker run -v shared:/tmp/git git-sync --repo=<REPO2> --root=/tmp/git --dest=repo2
```

Currently with this setup, git-sync complains when the --root directory is not empty requiring a cleanup. Is there any way to go around this? How about not cleaning up the --root directory?

**Comment by thockin** [comment]
The repo is checked out into the --root.  Git clone requires it to be empty. You have to use a different --root for each instance of git-sync, but you can send the --depth to a different dir, if you really need the links to be peers.

I have toyed with the idea of moving the repos to a different subdir under --root in v4, but didn't really see the value of it, as you would still need to distinguish between instances and it would make cleanup harder.

**Comment by ketozhang** [comment]
> The repo is checked out into the --root.

Is that because of the symlink switch implementation?

Normally you expect git clone to be done on root/dest as if I did

    cd root
    git clone URI DEST

**Comment by ketozhang** [comment]
I see that --dest was removed in the main branch. Now this changes the definition of what I meant by --root.

For all above, I was pertaining to 3.x branch

**Comment by ketozhang** [comment]
Understood thank you.

If I set each git-sync instance to --root /shared/repo1 and --root /shared/repo2 you end up getting this directory structure

    shared/
      repo1/repo1
      repo2/repo2

It's workable, but awkward.

**Comment by thockin** [comment]
I am on mobile so details may be fuzzy, but --dest can be an absolute path, so you can do:

Instance 1:
  --root /shared/root1
  --dest /shared/links

Instance 2:
  --root /shared/root2
  --dest /shared/links

You can probably even drop the "links" subdir

**Comment by thockin** [comment]
I just tried it and got something like:

```
lrwxrwxrwx 1 thockin primarygroup   43 Apr 20 18:52 1 -> r1/bb0128b883a7d8a48d04f9de714803afd24510e9
lrwxrwxrwx 1 thockin primarygroup   43 Apr 20 18:52 2 -> r2/e1a98273f6b03fc4893e5a94f73aaa81636adb7a
drwxr-xr-x 4 thockin primarygroup 4096 Apr 20 18:52 r1
drwxr-xr-x 4 thockin primarygroup 4096 Apr 20 18:52 r2
```
