### ISSUE TITLE
Add features that will make this compatible with `git daemon`

### ISSUE THREAD

**Issue by danielhoherd** [kubernetes/git-sync#724]
I have been attempting to use git-sync as a relay between an upstream git server with rate limits, and lots of tiny workers that need to clone the repo at rates that would exceed the upstream rate limits. I was unable to do this because of some limitations in how git-sync maintains the state of the git repo. I'm not sure of precisely what would need to change to make this work, but I observed that if you use `git daemon` to serve the contest of a `git-sync` maintained repo, the contents that are served by `git daemon` will never change after the initial clone. This appears to be because the HEAD in that repo is not updated when new contents are fetched. It also didn't seem possible to serve the contents of the workdirs that `git-sync` maintains because of some nuances of how `git daemon` expects the repo to be structured, such as the presence of the `.git/git-daemon-export-ok` which requires `.git` to be a directory.

**Comment by thockin** [comment]
I am open to use-cases, but git-sync works the way it does for a reason.

I have recently refactored it a lot, maybe you can try with a manual build
from the master branch?

**Comment by danielhoherd** [comment]
I tried to build the master branch but got a failure. I opened a ticket. https://github.com/kubernetes/git-sync/issues/731
