### ISSUE TITLE
sync git submodule 

### ISSUE THREAD

**Issue by jinseo-jang** [kubernetes/git-sync#75]
Hi there.
is it possible to synchronize git submodule as well?
if possible, I'd like to know how to use arguments.

**[e.g]**
_env:
  - name: GIT_SYNC_REPO
    value: {{ .Values.formsdesignerRepo }}
  - name: GIT_SYNC_USERNAME
    value: {{ .Values.githubUsername }}
  - name: GIT_SYNC_PASSWORD
    value: {{ .Values.githubPassword }}
  - name: GIT_SYNC_DEST
    value: git
  - name: GIT_SYNC_BRANCH_

**Comment by thockin** [comment]
That is not currently supported

**Comment by abh** [comment]
There's a patch in #62; it needs some more features before being merged it looks like -- but for basic use cases it works well.

**Comment by michallula** [comment]
it could be considered as done after merge of https://github.com/kubernetes/git-sync/pull/185 @thockin

**Comment by thockin** [comment]
fixed!
