### ISSUE TITLE
Possibility of a run webhook on startup?

### ISSUE THREAD

**Issue by sboardwell** [kubernetes/git-sync#750]
Would it be possible to have an option to run a webhook/exechook on startup in general, reagardless of whether a change is detected?

My use case is:
- an app is running with a git-sync sidecar container
- an init container is populating git-sync dest initially to avoid a race condition (checkout vs app start) 
- we are using a pvc instead of an emptydir to avoid having to perform a fresh checkout on each restart
- a webhook endpoint is available in the app to perform a task with the git-sync sources
- the task is either reload or restart depending on the changes

On first startup, and subsequent reloadable changes it is great. However, if the changes require a restart, the webhook is not triggered since no changes were detected at the time of restart.

I would therfore like to be able to run the webhook endpoint upon startup as a type of initialisation step. Does that make sense?

**Comment by thockin** [comment]
Is this the same solution as https://github.com/kubernetes/git-sync/issues/313 ?

**Comment by sboardwell** [comment]
Oh, yes. My use case is a different one, but the solution would work. Don't know if there could be a flag so as not to break current behaviour.

**Comment by sboardwell** [comment]
Whilst we are on the subject, a similar flag could be used for init containers as well.

I had the experience that an init container checks out, then the sidecar container takes over. However, on restart the init container hangs because there is no checkout necessary and no change detected (sync once waits for that one time) meaning the init container would hang until a change comes in.

Writing it out, I see it's not quite the same. Shall I open a new issue?

**Comment by thockin** [comment]
Running with `--one-time` should absolutely exit if the hash is already present.  If not, that's a bug.

**Comment by thockin** [comment]
I have a commit for fixing this (easy fix).  I chose not to add a flag for it, but I could be talked out of that.  I need to write a test still.

**Comment by thockin** [comment]
FWIW: the v4 branch handles --one-time correctly

**Comment by thockin** [comment]
Closing this as a dup of #313
