### ISSUE TITLE
Credentials specified by env vars not working

### ISSUE THREAD

**Issue by deyceg** [kubernetes/git-sync#77]
k8s cluster: v1.7.1
git-sync: v2.0.4/v2.0.5

The container fails to start because the credentials aren't passed to the `git` command. However, whats interesting is that if you `ssh` in to the container and run `git-sync --help` you can visibility see the env vars have been read by the go program and are set as "defaults".

If I override the container entrypoint and run `./git-sync -username <username> -password <password> then it works just fine.

This obviously isn't ideal because you can see the credentials in plaintext.

**Comment by thockin** [comment]
I don't know how to reproduce this.  @deyceg is there more detail you can provide?
