### ISSUE TITLE
Subsequent syncs fail due to destination path not being empty

### ISSUE THREAD

**Issue by stp-ip** [kubernetes/git-sync#8]
During some initial tests following error came up:
```text error syncing repo: error running command: exit status 128: "fatal: destination path '/etc/source' already exists and is not an empty directory.\n"```
This seems to only happen on subsequent sync runs. Before the directory is empty and syncs successfully.

Some ENVs for a better context:
        - name: GIT_SYNC_BRANCH
          value: master
        - name: GIT_SYNC_SSH
          value: "true"
        - name: GIT_SYNC_ONE_TIME
          value: "false"
        - name: GIT_SYNC_WAIT
          value: "2"
        - name: GIT_SYNC_ROOT
          value: /etc/source/
        - name: GIT_SYNC_DEST
          value: /etc/source/files

**Comment by TaiSHiNet** [comment]
Running into the same issue

**Comment by stp-ip** [comment]
Just as a sidenote the current workaround we use is to set GIT_SYNC_ONE_TIME to true and add a command "./git-sync && sleep 999d".
This prevents further syncs, but that is sorta acceptable in our current use case, as we deploy often enough.

**Comment by TaiSHiNet** [comment]
@stp-ip instead of the sleep, you could use pod inits:
http://kubernetes.io/docs/user-guide/production-pods/#handling-initialization

**Comment by stp-ip** [comment]
Yeah that works, if you wanna do only the initial sync. We actually want ongoing sync, but disabled it with GIT_SYNC_ONE_TIME and sleep due to the above bug.

**Comment by thockin** [comment]
DEST should be a bare name, "files" not "/path/to/files".  2.0.1 coming up :)

**Comment by thockin** [comment]
v2.0.1 is pushed with better help and an error in this case.  PTAL

**Comment by stp-ip** [comment]
That's there GIT_SYNC_ROOT comes in. Root basically should be used for the path and DEST should be used as the last folder name. Thanks for clarifying.

**Comment by stp-ip** [comment]
v2.0.1 is not showing up yet. See: https://gcr.io/v2/google_containers/git-sync/tags/list

**Comment by thockin** [comment]
Curiously it pushed git-sync-amd64 but not git-sync - will repush

**Comment by KingJ** [comment]
Would it be possible to update the [demo config](https://github.com/kubernetes/git-sync/blob/master/demo/config/pod.yaml) to reflect this? It uses `GIT_SYNC_DEST` as a path rather than bare name.

**Comment by thockin** [comment]
send a PR?  please :)

**Comment by thockin** [comment]
NM, I see it was fixed :)
