### ISSUE TITLE
Add webhook call on successful sync

### ISSUE THREAD

**Issue by andjelx** [kubernetes/git-sync#81]
I'd like to contribute into the project adding webhook call on successful sync.
The case is: we trigger Prometheus to reload it's alerts \ rules stored in git repo.

The parameters are as below:
```
var doWebhook = flag.Bool("webhook", envBool("WEBHOOK_ENABLED", false),
	"trigger webhook on sucessfull git sync")
var webhook = flag.String("webhook-url", envString("WEBHOOK_URL", ""),
	"the url to send a request to when git synced")
var webhookMethod = flag.String("webhook-method", envString("WEBHOOK_METHOD", "POST"),
	"the HTTP method url to use to send the webhook")
var webhookStatusCode = flag.Int("webhook-status-code", envInt("WEBHOOK_CODE", 200),
	"the HTTP status code indicating successful triggering of reload")
```

**Comment by emirozer** [comment]
Hey @andjelx are you working on this ?

I just started doing it today because, well having a very similar usecase..
https://github.com/emirozer/git-sync/commit/5aaffadae52ee201ff40dc78704373453ec12880
Its initial work only at the moment, so I'm gonna test & see if i can add something to the testing process about the hook as well. Do let me know if you already made progress?

**Comment by andjelx** [comment]
Actually I made it, it’s in my fork, but haven’t received any feedback here to raise a PR :(

**Comment by emirozer** [comment]
People are busy I guess :) why not raise the PR and discuss there, since it is going the be a very small change-set without side-effects to actually syncing ?

Ofc I'm not a maintainer so, no disrespect 🍻

**Comment by andjelx** [comment]
Initiated: https://github.com/kubernetes/git-sync/pull/85

**Comment by stp-ip** [comment]
Commented on the PR. Future feature issues might take a bit longer to respond due to priorities.

**Comment by thockin** [comment]
Sorry, it's been a hellish few weeks for me.  Will look at the PR.  In general I don't have a problem with this, but I'd prefer fewer flags.  What about something like `--webhook='{"url": "http://localhost:1234/reload", method="POST", success=200}'` - that block can be parsed as JSON, with unspecified keys having default values.

Unclear if success should be a specific code or a range.

**Comment by andjelx** [comment]
@thockin 
Your flags approach a good idea, but I just followed the same approach as in original code + technically passing ENV vars might be easier to use with K8 Deployments.

For now: success code is one code (not a range)

**Comment by andjelx** [comment]
@thockin What if we would go with existing approach with flags, then migrate to your approach ?

**Comment by stp-ip** [comment]
@andjelx that would already introduce them to the user and make the "upgrade" not backwards compatible.

**Comment by andjelx** [comment]
@stp-ip good point... I need then to dig more into Go then (as mostly on Python) how to process JSONs

**Comment by stp-ip** [comment]
Thanks for keeping the ball rolling. Looking forward to the next iteration.

**Comment by andjelx** [comment]
@stp-ip, @thockin I have updated PR
