### ISSUE TITLE
TODO: shellcheck test_e2e.sh and test_git.sh

### ISSUE THREAD

**Issue by thockin** [kubernetes/git-sync#891]
Its kind of a mess

**Comment by rul** [comment]
I'd like to give this a try. :slightly_smiling_face: 

/assign

**Comment by thockin** [comment]
Retitled to reference test_git.sh :)

**Comment by thockin** [comment]
test_e2e.sh is done - now for test_git.sh ?

**Comment by rul** [comment]
> test_e2e.sh is done - now for test_git.sh ?

Yup! Will put up a PR soon.
