### ISSUE TITLE
Question: Usage outside kubernetes?

### ISSUE THREAD

**Issue by geekdave** [kubernetes/git-sync#90]
Wondering if this can be used as a standalone docker container outside of kubernetes.  I see in docs/ssh.md, it mentions using kubernetes secrets.  I'd like to use git over ssh, with public key auth, but just on a standalone VM running docker.

Thanks!

**Comment by thockin** [comment]
It should work fine.  Kubernetes secrets are just one way to poulate config
files (volume mounts) and env vars.
