### ISSUE TITLE
git-sync produced an intermediate file，the path of command is wrong

### ISSUE THREAD

**Issue by JumpWill** [kubernetes/git-sync#909]
i wanna use git sync to update code in time,
as for my case， the workdir of pod and commnd is /repo/repo,
and the location of git repo is also  /repo/repo。
git-sync produced an intermediate file，like xxxxx，
when i reload my service ， the path of command will be xxxx， not /repo/repo，
how can i fix this ？

**Comment by thockin** [comment]
git-sync works in a non-checked-out repository and then creates worktrees for specific SHAs.  Those appear as directories.

The `--root` flag to git-sync is not where the code will be checked out, that's the directory under which git-sync operates.  In there you will find a symlink which points to the current worktree.  This lets us do atomic updates when the remote is changed.

If that does not explain, then I need you to provide more information.
