### ISSUE TITLE
Git Sync Init giving a Permission Denied Error

### ISSUE THREAD

**Issue by ahipp13** [kubernetes/git-sync#927]
Hello git sync community,

I am reaching out because I am having a problem that I am sure is an easy fix I just don't know what to do.

We are running git sync on Kubernetes, and recently the nodes got upgraded from RHEL 8 to RHEL 9.4. Now when my git-sync-init containers try to run, I am getting this error:

INFO: detected pid 1, running init handler
{"logger":"","ts":"2024-11-06 16:58:01.096832","caller":{"file":"main.go","line":424},"level":0,"msg":"setting --ref from deprecated --branch"}
{"logger":"","ts":"2024-11-06 16:58:01.097168","caller":{"file":"main.go","line":456},"level":0,"msg":"setting --link from deprecated --dest"}
{"logger":"","ts":"2024-11-06 16:58:01.097189","caller":{"file":"main.go","line":506},"level":0,"msg":"setting --max-failures from deprecated --max-sync-failures"}
{"logger":"","ts":"2024-11-06 16:58:01.097240","caller":{"file":"main.go","line":626},"level":0,"msg":"starting up","version":"v4.3.0","pid":11,"uid":50000,"gid":50000,"home":"/tmp","flags":[]}
{"logger":"","ts":"2024-11-06 16:58:01.097449","caller":{"file":"main.go","line":700},"msg":"FATAL: can't add user","error":"open /etc/passwd: permission denied"}

Could anybody explain to me why this would be happening and how to fix?? On the older nodes it runs just fine. The git sync version I am using is 4.3.0. I am running it as a part of my Airflow deployment.

Any tip0s or suggestions would be GREATLY appreciated. Thank you!!!

**Comment by thockin** [comment]
That would imply either:
- the Pod config has changed (e.g. you started using `--add-user`, or the `RunAsUser` changed
- something is mounting /etc/passwd from outside the pod with different permissions

if you run the git-sync image but set `command` to `[sleep, inf]`, then shell in, what does /etc/passwd look like?

For example, running just as a docker container:

```
$ docker run -ti --entrypoint=sh registry.k8s.io/git-sync/git-sync:v4.3.0

sh-5.2$ ls -l /etc/passwd 
-rw-rw-rw- 1 root root 882 Sep 25 18:46 /etc/passwd

sh-5.2$ id 
uid=65533(git-sync) gid=65533(git-sync) groups=65533(git-sync)

sh-5.2$ tail -n3 /etc/passwd
_apt:x:42:65534::/nonexistent:/usr/sbin/nologin
nobody:x:65534:65534:nobody:/nonexistent:/usr/sbin/nologin
git-sync:x:65533:65533::/tmp:/sbin/nologin
```

**Comment by ahipp13** [comment]
Yup, that was the issue! It was running with a different UID, and for some reason on the older RHEL version it worked but on the newer RHEL version it didn't. Updated the UID of the container to use that 65533 and it works now. Thank you so much for the quick response!
